import { CommonModule } from '@angular/common';
import { Component, EventEmitter, Input, OnChanges, Output, SimpleChanges } from '@angular/core';
import { FormsModule } from '@angular/forms';
import { AuthApiService } from '../../core/auth-api.service';

@Component({
  selector: 'app-student-profile-onboarding',
  standalone: true,
  imports: [CommonModule, FormsModule],
  styles: [`
    :host{display:block;min-height:100vh;background:#f4f7f5;color:#15221b;font-family:"DM Sans",sans-serif}.profile-header{height:68px;padding:0 clamp(20px,4vw,62px);display:flex;align-items:center;border-bottom:1px solid #dce4df;background:#fff}.brand{display:flex;align-items:center;gap:10px;font-size:20px;font-weight:900}.brand span{width:32px;height:32px;display:grid;place-items:center;border-radius:9px;background:#102f45;color:#64cfb0}.header-actions{margin-left:auto;display:flex;gap:14px}.header-actions button{border:0;background:transparent;color:#5f6e66;font-weight:800;cursor:pointer}
    .profile-shell{max-width:1120px;margin:auto;padding:54px 24px 80px}.intro{display:grid;grid-template-columns:1fr auto;gap:30px;align-items:end;margin-bottom:28px}.eyebrow{color:#087a50;font-size:11px;font-weight:900;letter-spacing:.16em}.intro h1{font-size:clamp(34px,5vw,58px);letter-spacing:-.05em;margin:9px 0 10px}.intro p{max-width:700px;color:#68766e;line-height:1.6;margin:0}.progress{min-width:180px;text-align:right}.progress strong{font-size:28px;color:#087a50}.progress small{display:block}.progress span{display:block;height:7px;margin-top:8px;border-radius:99px;background:#dfe7e2;overflow:hidden}.progress i{display:block;height:100%;background:#087a50}
    .stepper{display:grid;grid-template-columns:repeat(4,1fr);margin-bottom:18px;background:#fff;border:1px solid #dbe4de;border-radius:14px;overflow:hidden}.stepper button{padding:17px 14px;border:0;border-right:1px solid #e2e8e4;background:#fff;text-align:left;color:#7a867f;cursor:pointer}.stepper button:last-child{border:0}.stepper button.active{background:#eaf5ef;color:#087a50}.stepper b,.stepper small{display:block}.stepper b{font-size:12px}.stepper small{font-size:9px;margin-top:3px}
    form{background:#fff;border:1px solid #dbe4de;border-radius:16px;padding:clamp(24px,4vw,45px);box-shadow:0 18px 55px rgba(20,46,30,.06)}.form-heading{margin-bottom:25px}.form-heading span{color:#087a50;font-size:10px;font-weight:900;letter-spacing:.12em}.form-heading h2{font-size:27px;margin:7px 0}.form-heading p{color:#718078;margin:0}.grid{display:grid;grid-template-columns:1fr 1fr;gap:18px 20px}.wide{grid-column:1/-1}label{display:flex;flex-direction:column;gap:8px;color:#34443b;font-size:12px;font-weight:800}input,select{height:52px;border:1px solid #cbd8d0;border-radius:10px;padding:0 14px;background:#fff;font:inherit;outline:0}input:focus,select:focus{border-color:#087a50;box-shadow:0 0 0 3px #e2f2e9}.check-row{display:flex;gap:18px;flex-wrap:wrap;padding:14px;border-radius:10px;background:#f4f8f6}.check-row label{flex-direction:row;align-items:center}.check-row input{width:18px;height:18px}.hint{font-size:10px;color:#7b8780;font-weight:500}.message{padding:12px 14px;border-radius:9px;margin:18px 0 0}.error{background:#fff0ee;color:#a43a2d}.actions{display:flex;justify-content:space-between;gap:12px;margin-top:30px;padding-top:22px;border-top:1px solid #e4e9e6}.actions button{border-radius:9px;padding:12px 20px;font-weight:900;cursor:pointer}.secondary{border:1px solid #ccd8d1;background:#fff}.primary{margin-left:auto;border:1px solid #087a50;background:#087a50;color:#fff}.primary:disabled{opacity:.5}
    @media(max-width:720px){.intro{grid-template-columns:1fr}.progress{text-align:left}.stepper{grid-template-columns:1fr 1fr}.grid{grid-template-columns:1fr}.wide{grid-column:auto}.profile-shell{padding-top:32px}.profile-header{padding:0 16px}}
  `],
  template: `
    <header class="profile-header"><div class="brand"><span>S</span>SuperOffer</div><div class="header-actions"><button *ngIf="profile?.profile_complete" (click)="offersRequested.emit()">Offers</button><button (click)="signedOut.emit()">Logout</button></div></header>
    <main class="profile-shell">
      <section class="intro"><div><span class="eyebrow">STUDENT PROFILE</span><h1>{{profile?.profile_complete ? 'Update your profile.' : 'Create your profile.'}}</h1><p>Universities and education-loan providers use this information to determine eligibility and prepare relevant offers. Your contact details stay private.</p></div><div class="progress"><strong>{{progress}}%</strong><small>Profile completion</small><span><i [style.width.%]="progress"></i></span></div></section>
      <nav class="stepper"><button type="button" *ngFor="let item of steps; let i=index" [class.active]="step===i" (click)="step=i"><b>0{{i+1}} · {{item.title}}</b><small>{{item.copy}}</small></button></nav>
      <form (ngSubmit)="continue()" #profileForm="ngForm">
        <section *ngIf="step===0"><div class="form-heading"><span>PERSONAL DETAILS</span><h2>Tell us about yourself</h2><p>These details support admissions and visa eligibility checks.</p></div><div class="grid">
          <label>Date of birth<input type="date" name="dob" [(ngModel)]="form.date_of_birth" required></label><label>Nationality<input name="nationality" [(ngModel)]="form.nationality" placeholder="e.g. Indian" required></label><label class="wide">Current city and country<input name="location" [(ngModel)]="form.location" placeholder="e.g. Mumbai, India" required></label>
        </div></section>
        <section *ngIf="step===1"><div class="form-heading"><span>ACADEMIC BACKGROUND</span><h2>Your latest qualification</h2><p>Enter the academic record universities should evaluate.</p></div><div class="grid">
          <label class="wide">Institution name<input name="institution" [(ngModel)]="form.institution_name" required></label><label>Qualification<input name="qualification" [(ngModel)]="form.qualification" placeholder="B.Tech Computer Science" required></label><label>Graduation year<input name="graduation" type="number" min="1990" max="2035" [(ngModel)]="form.graduation_year" required></label><label>Grading system<select name="grading" [(ngModel)]="form.grading_system" required><option value="">Select system</option><option>Percentage</option><option>CGPA / 10</option><option>GPA / 4</option><option>Other</option></select></label><label>Score / grade<input name="score" [(ngModel)]="form.score_raw" placeholder="e.g. 8.8 / 10" required></label><label>English or entrance test<select name="testType" [(ngModel)]="form.test_type" required><option value="">Select test</option><option>IELTS</option><option>TOEFL</option><option>PTE</option><option>GRE</option><option>GMAT</option><option>Not yet taken</option></select></label><label>Test score<input name="testScore" [(ngModel)]="form.test_score" placeholder="e.g. 7.5 or Planned" required></label>
        </div></section>
        <section *ngIf="step===2"><div class="form-heading"><span>STUDY PREFERENCES</span><h2>What are you looking for?</h2><p>This powers matching for university admissions and scholarships.</p></div><div class="grid">
          <label>Target countries<input name="countries" [(ngModel)]="form.target_countries" placeholder="Canada, United Kingdom" required><small class="hint">Separate multiple countries with commas.</small></label><label>Target courses<input name="courses" [(ngModel)]="form.target_courses" placeholder="Data Science, Artificial Intelligence" required></label><label>Degree level<select name="degreeLevel" [(ngModel)]="form.degree_level" required><option value="">Select level</option><option>Bachelors</option><option>Masters</option><option>MBA</option><option>Doctorate</option><option>Diploma</option></select></label><label>Preferred intake<input name="intake" [(ngModel)]="form.intake_term" placeholder="Fall 2027" required></label>
        </div></section>
        <section *ngIf="step===3"><div class="form-heading"><span>FUNDING & PRIVACY</span><h2>Complete your matching preferences</h2><p>Loan providers use funding information only to assess relevant products.</p></div><div class="grid">
          <label>Study budget<select name="budget" [(ngModel)]="form.budget_band" required><option value="">Select total budget</option><option>Under ₹15 lakh</option><option>₹15–25 lakh</option><option>₹25–40 lakh</option><option>₹40–60 lakh</option><option>Above ₹60 lakh</option></select></label><label>Primary funding source<select name="funding" [(ngModel)]="form.funding_source" required><option value="">Select source</option><option>Education loan</option><option>Family savings</option><option>Scholarship</option><option>Mixed funding</option></select></label><div class="wide check-row"><label><input type="checkbox" name="scholarship" [(ngModel)]="form.scholarship_need"> I need scholarship support</label><label><input type="checkbox" name="universities" [(ngModel)]="form.visible_to_universities"> Show me to verified universities</label><label><input type="checkbox" name="lenders" [(ngModel)]="form.visible_to_loan_providers"> Show me to verified loan providers</label></div>
        </div></section>
        <p class="message error" *ngIf="error">{{error}}</p><footer class="actions"><button type="button" class="secondary" *ngIf="step>0" (click)="step=step-1">← Back</button><button class="primary" [disabled]="saving || profileForm.invalid">{{saving ? 'Saving…' : step<3 ? 'Continue →' : 'Save profile and view offers →'}}</button></footer>
      </form>
    </main>
  `
})
export class StudentProfileOnboardingComponent implements OnChanges {
  @Input() profile: any; @Input() token = '';
  @Output() completed = new EventEmitter<any>(); @Output() offersRequested = new EventEmitter<void>(); @Output() signedOut = new EventEmitter<void>();
  step = 0; saving = false; error = '';
  steps = [{title:'Personal',copy:'Identity and location'},{title:'Academics',copy:'Education and tests'},{title:'Preferences',copy:'Study goals'},{title:'Funding',copy:'Budget and visibility'}];
  form: any = {date_of_birth:'',nationality:'',location:'',institution_name:'',qualification:'',grading_system:'',score_raw:'',graduation_year:'',test_type:'',test_score:'',target_countries:'',target_courses:'',degree_level:'',intake_term:'',budget_band:'',scholarship_need:false,funding_source:'',visible_to_universities:true,visible_to_loan_providers:true};
  constructor(private api: AuthApiService) {}
  ngOnChanges(changes: SimpleChanges) {
    if (!changes['profile'] || !this.profile) return;
    const a=this.profile.academic_records?.[0]||{}, t=this.profile.test_scores?.[0]||{}, p=this.profile.preferences||{}, f=this.profile.financial||{}, v=this.profile.visibility||{};
    Object.assign(this.form,{date_of_birth:this.profile.date_of_birth||'',nationality:this.profile.nationality||'',location:this.profile.location||'',institution_name:a.institution_name||'',qualification:a.qualification||'',grading_system:a.grading_system||'',score_raw:a.score_raw||'',graduation_year:a.graduation_year||'',test_type:t.test_type||'',test_score:t.score||'',target_countries:(p.target_countries||[]).join(', '),target_courses:(p.target_courses||[]).join(', '),degree_level:p.degree_level||'',intake_term:p.intake_term||'',budget_band:p.budget_band||'',scholarship_need:Boolean(p.scholarship_need),funding_source:f.funding_source||'',visible_to_universities:v.visible_to_universities!==false,visible_to_loan_providers:v.visible_to_loan_providers!==false});
  }
  get progress(){const fields=['date_of_birth','nationality','location','institution_name','qualification','graduation_year','grading_system','score_raw','test_type','test_score','target_countries','target_courses','degree_level','intake_term','budget_band','funding_source'];return Math.round(fields.filter(k=>String(this.form[k]??'').trim()).length/fields.length*100);}
  async continue(){
    if(this.step<3){this.step++;return;} this.saving=true;this.error='';
    try{const split=(v:string)=>v.split(',').map(x=>x.trim()).filter(Boolean);const saved=await this.api.updateStudentProfile(this.token,{date_of_birth:this.form.date_of_birth,nationality:this.form.nationality.trim(),location:this.form.location.trim(),academic_records:[{institution_name:this.form.institution_name.trim(),qualification:this.form.qualification.trim(),grading_system:this.form.grading_system,score_raw:this.form.score_raw.trim(),graduation_year:Number(this.form.graduation_year)}],test_scores:[{test_type:this.form.test_type,score:this.form.test_score.trim()}],preferences:{target_countries:split(this.form.target_countries),target_courses:split(this.form.target_courses),degree_level:this.form.degree_level,intake_term:this.form.intake_term.trim(),budget_band:this.form.budget_band,scholarship_need:Boolean(this.form.scholarship_need)},financial:{funding_source:this.form.funding_source},visibility:{visible:true,visible_to_universities:Boolean(this.form.visible_to_universities),visible_to_loan_providers:Boolean(this.form.visible_to_loan_providers),visible_to_consultants:false}});if(!saved.profile_complete)throw new Error('Please complete every required profile field before viewing offers.');this.completed.emit(saved);}catch(e){this.error=e instanceof Error?e.message:'Your profile could not be saved.';}finally{this.saving=false;}
  }
}
