[variables]
NIXPACKS_NODE_VERSION = "22"

[phases.install]
cmds = ["npm ci"]

[phases.build]
cmds = ["npm run build"]

[start]
cmd = "npx serve -s dist/superoffer/browser -l tcp://0.0.0.0:${PORT:-3000}"
