import { CommonModule } from '@angular/common';
import { Component, EventEmitter, Input, OnChanges, Output } from '@angular/core';
import { FormsModule } from '@angular/forms';
import { AuthApiService } from '../../core/auth-api.service';

@Component({
  selector:'app-student-profile-onboarding', standalone:true, imports:[CommonModule,FormsModule],
  styleUrls:['../../onboarding-typography.css'],
  styles:[`
    :host{--green:#087a50;--line:#dfe6e1;--muted:#6d7972;display:block;min-height:100vh;background:#fff;color:#172019;font-family:"DM Sans",sans-serif}.student-head{height:64px;padding:0 28px;display:flex;align-items:center;border-bottom:1px solid var(--line)}.brand{display:flex;align-items:center;gap:9px;font-size:19px;font-weight:900}.brand span{width:29px;height:29px;display:grid;place-items:center;border-radius:8px;background:#102f45;color:#68d1b4}.head-actions{margin-left:auto;display:flex;gap:16px}.head-actions button{border:0;background:none;color:#5f6d65;font-weight:800;cursor:pointer}
    .content.onboarding{height:calc(100vh - 64px);overflow:hidden}.onboarding-top{display:flex;justify-content:space-between;align-items:center}.progress-summary{width:240px;text-align:right}.progress-summary strong,.progress-summary small{display:block}.progress-summary span{height:6px;background:#dfe8e3;display:block;border-radius:99px;margin:6px 0;overflow:hidden}.progress-summary i{display:block;height:100%;background:var(--green)}
    .form-title{margin-bottom:18px}.form-title span{color:var(--green);font-size:10px;font-weight:900;letter-spacing:.12em}.form-title h2{font-size:25px;margin:6px 0}.form-title p{color:var(--muted);margin:0}.form-grid{display:grid;grid-template-columns:1fr 1fr;gap:16px 20px}.wide{grid-column:1/-1}label{display:flex;flex-direction:column;gap:7px;font-weight:800;font-size:12px}input,select,textarea{border:1px solid #cbd8d0;border-radius:9px;padding:12px;font:inherit;background:#fff}textarea{min-height:86px;resize:vertical}.choice-grid{display:grid;grid-template-columns:1fr 1fr;gap:16px}.choice-grid button{padding:28px;border:1px solid var(--line);border-radius:13px;background:#fff;text-align:left;cursor:pointer}.choice-grid button.selected{border-color:var(--green);background:#edf8f2}.choice-grid strong,.choice-grid small{display:block}.choice-grid strong{font-size:17px}.choice-grid small{margin-top:7px;color:var(--muted)}.exam-grid{display:grid;gap:10px}.exam-row{display:grid;grid-template-columns:100px 100px 1fr 1fr;gap:10px;align-items:center;padding:12px;border-radius:10px;background:#f5f8f6}.check{flex-direction:row;align-items:center}.check input{width:18px;height:18px}.document-grid{display:grid;grid-template-columns:1fr 1fr;gap:12px}.document-card{padding:15px;border:1px solid var(--line);border-radius:10px}.document-card strong,.document-card small{display:block}.document-card small{color:var(--muted);margin:4px 0 10px}.review-grid{display:grid;grid-template-columns:1fr 1fr 1fr;gap:12px}.review-grid article{padding:17px;background:#f4f8f6;border-radius:10px}.review-grid strong,.review-grid small{display:block}.review-grid small{color:var(--muted);margin-bottom:5px}.save-message{padding:11px;border-radius:8px;margin-top:15px}.error{background:#fff0ee;color:#a43b2e}.success{background:#e9f7f0;color:#087a50}.form-actions{display:flex;justify-content:space-between;margin-top:24px;padding-top:18px;border-top:1px solid var(--line)}.form-actions button{padding:11px 18px;border-radius:8px;font-weight:900;cursor:pointer}.secondary{background:#fff;border:1px solid #cbd7d0}.primary{margin-left:auto;background:var(--green);color:#fff;border:1px solid var(--green)}.primary:disabled{opacity:.5}.tag-hint{color:var(--muted);font-size:10px}
    @media(max-width:720px){.content.onboarding{height:auto;overflow:visible}.form-grid,.choice-grid,.document-grid,.review-grid{grid-template-columns:1fr}.wide{grid-column:auto}.exam-row{grid-template-columns:1fr 1fr}.onboarding-top{align-items:flex-start;flex-direction:column}.progress-summary{width:100%;text-align:left}.student-head{padding:0 14px}}
  `],
  template:`
    <header class="student-head"><div class="brand"><span>S</span>SuperOffer</div><div class="head-actions"><button *ngIf="profile?.profileComplete" (click)="offersRequested.emit()">Offers</button><button (click)="signedOut.emit()">Logout</button></div></header>
    <main class="content onboarding">
      <header class="onboarding-top"><div><span class="eyebrow">STUDENT PROFILE</span><h1>{{profile?.profileComplete?'Update your profile':'Build your opportunity profile'}}</h1><p>Save every step and return whenever you need.</p></div><div class="progress-summary"><strong>{{completion}}% complete</strong><span><i [style.width.%]="completion"></i></span><small>{{completedSections}} of 6 profile sections completed</small></div></header>
      <div class="onboarding-layout">
        <aside class="profile-drawer"><div class="profile-drawer-head"><div><small>YOUR JOURNEY</small><strong>Profile builder</strong></div></div><span class="journey-label">9 STEPS</span><button *ngFor="let item of steps;let i=index" [class.current]="step===i" [class.complete]="isStepComplete(i)" (click)="step=i"><span>{{isStepComplete(i)?'✓':i+1}}</span><div><strong>{{item.title}}</strong><small>{{item.copy}}</small></div></button></aside>
        <form class="profile-form" (ngSubmit)="next()" #stepForm="ngForm">
          <section *ngIf="step===0"><div class="form-title"><span>STEP 1</span><h2>Personal information</h2><p>Your identity and contact details remain private until you accept an offer.</p></div><div class="form-grid">
            <label>First name<input name="firstName" [(ngModel)]="form.firstName" required></label><label>Last name<input name="lastName" [(ngModel)]="form.lastName" required></label><label>Profile photo URL<input name="photo" [(ngModel)]="form.profilePhoto" placeholder="https://"></label><label>Date of birth<input type="date" name="dob" [(ngModel)]="form.dateOfBirth" required></label><label>Gender<select name="gender" [(ngModel)]="form.gender" required><option value="">Select</option><option>Female</option><option>Male</option><option>Non-binary</option><option>Prefer not to say</option></select></label><label>Nationality<input name="nationality" [(ngModel)]="form.nationality" required></label><label>Country<input name="country" [(ngModel)]="form.country" required></label><label>State<input name="state" [(ngModel)]="form.state" required></label><label>City<input name="city" [(ngModel)]="form.city" required></label><label>Phone number<input name="phone" [(ngModel)]="form.phoneNumber" placeholder="+91…" required></label><label class="wide">Address<input name="address" [(ngModel)]="form.address" required></label><label>Passport status<select name="passportStatus" [(ngModel)]="form.passportStatus" required><option value="">Select</option><option>Available</option><option>Applied</option><option>Not available</option></select></label><label>Passport number (optional)<input name="passportNumber" [(ngModel)]="form.passportNumber"></label><label class="wide">Short bio<textarea name="bio" [(ngModel)]="form.shortBio" required></textarea></label>
          </div></section>
          <section *ngIf="step===1"><div class="form-title"><span>STEP 2</span><h2>Where are you studying now?</h2><p>We adapt the next step to your education level.</p></div><div class="choice-grid"><button type="button" [class.selected]="form.studentType==='SCHOOL'" (click)="form.studentType='SCHOOL'"><strong>School student</strong><small>Grades 10–12, boards, subjects and predicted marks</small></button><button type="button" [class.selected]="form.studentType==='COLLEGE'" (click)="form.studentType='COLLEGE'"><strong>College student</strong><small>Degree, CGPA, semesters, projects and internships</small></button></div></section>
          <section *ngIf="step===2"><div class="form-title"><span>STEP 3</span><h2>Education details</h2><p>Give institutions the academic evidence needed to evaluate you.</p></div><div class="form-grid" *ngIf="form.studentType==='SCHOOL'">
            <label>School name<input name="schoolName" [(ngModel)]="form.schoolName" required></label><label>Education board<input name="board" [(ngModel)]="form.educationBoard" required></label><label>Current grade<input name="grade" [(ngModel)]="form.currentGrade" required></label><label>10th marks<input name="marks10" [(ngModel)]="form.marks10" required></label><label>11th marks<input name="marks11" [(ngModel)]="form.marks11"></label><label>12th / predicted marks<input name="marks12" [(ngModel)]="form.marks12"></label><label>Graduation year<input type="number" name="schoolYear" [(ngModel)]="form.graduationYear" required></label><label>Subjects<input name="subjects" [(ngModel)]="form.subjects" required><small class="tag-hint">Comma separated</small></label><label class="wide">Academic achievements<textarea name="schoolAchievements" [(ngModel)]="form.academicAchievements"></textarea></label>
          </div><div class="form-grid" *ngIf="form.studentType==='COLLEGE'">
            <label>College name<input name="collegeName" [(ngModel)]="form.collegeName" required></label><label>University<input name="university" [(ngModel)]="form.university" required></label><label>Degree<input name="degree" [(ngModel)]="form.degree" required></label><label>Department<input name="department" [(ngModel)]="form.department" required></label><label>CGPA / 10<input type="number" step=".01" name="cgpa" [(ngModel)]="form.cgpa" required></label><label>Current semester<input name="semester" [(ngModel)]="form.currentSemester" required></label><label>Number of backlogs<input type="number" min="0" name="backlogs" [(ngModel)]="form.numberOfBacklogs" required></label><label>Graduation year<input type="number" name="collegeYear" [(ngModel)]="form.graduationYear" required></label><label>Projects<input name="projects" [(ngModel)]="form.projects"></label><label>Internships<input name="internships" [(ngModel)]="form.internships"></label><label class="wide">Academic achievements<textarea name="collegeAchievements" [(ngModel)]="form.academicAchievements"></textarea></label>
          </div></section>
          <section *ngIf="step===3"><div class="form-title"><span>STEP 4</span><h2>Study preferences</h2><p>Tell universities what kind of opportunity you want.</p></div><div class="form-grid">
            <label>Preferred countries<input name="countries" [(ngModel)]="form.preferredCountries" required></label><label>Preferred courses<input name="courses" [(ngModel)]="form.preferredCourses" required></label><label>Degree type<input name="degreeType" [(ngModel)]="form.degreeType" required></label><label>Preferred intake<input name="intake" [(ngModel)]="form.preferredIntake" required></label><label>Budget range<input name="budget" [(ngModel)]="form.budgetRange" required></label><label class="check"><input type="checkbox" name="scholarship" [(ngModel)]="form.scholarshipRequired"> Scholarship required</label><label class="check"><input type="checkbox" name="accommodation" [(ngModel)]="form.accommodationRequired"> Accommodation required</label>
          </div></section>
          <section *ngIf="step===4"><div class="form-title"><span>STEP 5</span><h2>English & entrance exams</h2><p>Add every exam—even if you have not taken it yet.</p></div><div class="exam-grid"><div class="exam-row" *ngFor="let exam of form.exams;let i=index"><strong>{{exam.examType}}</strong><label class="check"><input type="checkbox" [name]="'taken'+i" [(ngModel)]="exam.examTaken"> Taken</label><input type="number" [name]="'score'+i" [(ngModel)]="exam.score" [disabled]="!exam.examTaken" placeholder="Score"><input type="date" [name]="'date'+i" [(ngModel)]="exam.examDate" [disabled]="!exam.examTaken"></div></div></section>
          <section *ngIf="step===5"><div class="form-title"><span>STEP 6</span><h2>Skills</h2><p>Show the abilities you bring beyond grades.</p></div><div class="form-grid"><label>Technical skills<input name="technical" [(ngModel)]="form.technicalSkills" required></label><label>Soft skills<input name="soft" [(ngModel)]="form.softSkills" required></label><label>Languages known<input name="languages" [(ngModel)]="form.languagesKnown" required></label><label>Certifications<input name="certifications" [(ngModel)]="form.certifications"></label></div></section>
          <section *ngIf="step===6"><div class="form-title"><span>STEP 7</span><h2>Achievements & links</h2><p>Add evidence of initiative, leadership and work.</p></div><div class="form-grid"><label>Hackathons<input name="hackathons" [(ngModel)]="form.hackathons"></label><label>Competitions<input name="competitions" [(ngModel)]="form.competitions"></label><label>Volunteer experience<input name="volunteer" [(ngModel)]="form.volunteerExperience"></label><label>Leadership experience<input name="leadership" [(ngModel)]="form.leadershipExperience"></label><label>Portfolio URL<input name="portfolio" type="url" [(ngModel)]="form.portfolioUrl"></label><label>LinkedIn URL<input name="linkedin" type="url" [(ngModel)]="form.linkedInUrl"></label><label>GitHub URL<input name="github" type="url" [(ngModel)]="form.githubUrl"></label></div></section>
          <section *ngIf="step===7"><div class="form-title"><span>STEP 8</span><h2>Documents</h2><p>PDF, JPG, PNG, DOC or DOCX. Maximum 10 MB per file.</p></div><div class="document-grid"><div class="document-card" *ngFor="let doc of documentTypes"><strong>{{doc.label}}</strong><small>{{uploaded(doc.type)?'Uploaded · verification pending':'Not uploaded'}}</small><input type="file" (change)="chooseFile(doc.type,$event)" [accept]="acceptedFiles"><button type="button" class="secondary" [disabled]="!pendingFiles[doc.type]" (click)="upload(doc.type)">Upload</button></div></div></section>
          <section *ngIf="step===8"><div class="form-title"><span>STEP 9</span><h2>Review your profile</h2><p>Complete missing sections before opening your offer workspace.</p></div><div class="review-grid"><article *ngFor="let section of sectionReview"><small>{{section.label}}</small><strong>{{section.done?'Complete':'Needs attention'}}</strong></article></div><p class="save-message success" *ngIf="completion===100">Your profile is complete and ready for matching.</p></section>
          <p class="save-message error" *ngIf="error">{{error}}</p><p class="save-message success" *ngIf="message">{{message}}</p>
          <footer class="form-actions"><button type="button" class="secondary" *ngIf="step>0" (click)="step=step-1">← Back</button><button class="primary" [disabled]="saving || (step===1&&!form.studentType)">{{saving?'Saving…':step===8?'View my offers →':'Save & continue →'}}</button></footer>
        </form>
      </div>
    </main>`
})
export class StudentProfileOnboardingComponent implements OnChanges {
  @Input() profile:any; @Input() token=''; @Output() completed=new EventEmitter<any>(); @Output() offersRequested=new EventEmitter<void>(); @Output() signedOut=new EventEmitter<void>();
  step=0;saving=false;error='';message='';acceptedFiles='.pdf,.jpg,.jpeg,.png,.doc,.docx';pendingFiles:Record<string,File>={};
  steps=[{title:'Personal',copy:'Identity & contact'},{title:'Student type',copy:'School or college'},{title:'Education',copy:'Academic record'},{title:'Preferences',copy:'Study goals'},{title:'Exams',copy:'Scores & dates'},{title:'Skills',copy:'Capabilities'},{title:'Achievements',copy:'Experience & links'},{title:'Documents',copy:'Evidence'},{title:'Review',copy:'Submit profile'}];
  documentTypes=[['PASSPORT','Passport'],['RESUME','Resume'],['ACADEMIC_TRANSCRIPT','Academic transcript'],['STATEMENT_OF_PURPOSE','Statement of purpose'],['RECOMMENDATION_LETTER','Recommendation letter'],['ENGLISH_TEST_CERTIFICATE','English test certificate'],['CERTIFICATE','Certificates'],['OTHER','Other supporting document']].map(([type,label])=>({type,label}));
  form:any={firstName:'',lastName:'',profilePhoto:'',dateOfBirth:'',gender:'',nationality:'',country:'',state:'',city:'',address:'',phoneNumber:'',passportStatus:'',passportNumber:'',shortBio:'',studentType:'',schoolName:'',educationBoard:'',currentGrade:'',marks10:'',marks11:'',marks12:'',graduationYear:'',subjects:'',academicAchievements:'',collegeName:'',university:'',degree:'',department:'',cgpa:'',currentSemester:'',numberOfBacklogs:0,projects:'',internships:'',preferredCountries:'',preferredCourses:'',degreeType:'',preferredIntake:'',budgetRange:'',scholarshipRequired:false,accommodationRequired:false,exams:['IELTS','TOEFL','PTE','DUOLINGO','SAT','GRE','GMAT'].map(examType=>({examType,examTaken:false,score:null,examDate:null})),technicalSkills:'',softSkills:'',languagesKnown:'',certifications:'',hackathons:'',competitions:'',volunteerExperience:'',leadershipExperience:'',portfolioUrl:'',linkedInUrl:'',githubUrl:''};
  constructor(private api:AuthApiService){}
  ngOnChanges(){if(!this.profile)return;const p=this.profile.personal||{},e=this.profile.education||{},pr=this.profile.preferences||{},s=this.profile.skills||{};Object.assign(this.form,p,{studentType:e.studentType||'',...(e.school||{}),...(e.college||{}),graduationYear:e.school?.graduationYear||e.college?.graduationYear||'',subjects:this.join(e.school?.subjects),academicAchievements:this.join(e.school?.academicAchievements||e.college?.academicAchievements),projects:this.join(e.college?.projects),internships:this.join(e.college?.internships),preferredCountries:this.join(pr.preferredCountries),preferredCourses:this.join(pr.preferredCourses),...pr,technicalSkills:this.join(s.technicalSkills),softSkills:this.join(s.softSkills),languagesKnown:this.join(s.languagesKnown),certifications:this.join(s.certifications),hackathons:this.join(s.hackathons),competitions:this.join(s.competitions),volunteerExperience:this.join(s.volunteerExperience),leadershipExperience:this.join(s.leadershipExperience),portfolioUrl:s.portfolioUrl||'',linkedInUrl:s.linkedInUrl||'',githubUrl:s.githubUrl||''});if(this.profile.exams?.exams)this.form.exams=this.form.exams.map((x:any)=>this.profile.exams.exams.find((y:any)=>y.examType===x.examType)||x);}
  get completion(){return this.profile?.profileCompletionPercentage||0} get completedSections(){return Object.values(this.profile?.sections||{}).filter(Boolean).length} get sectionReview(){return Object.entries(this.profile?.sections||{}).map(([key,done])=>({label:key[0].toUpperCase()+key.slice(1),done}))}
  isStepComplete(i:number){const map=['personal',null,'education','preferences','exams',null,'skills','documents',null];return map[i]?Boolean(this.profile?.sections?.[map[i] as string]):false}
  split(v:string){return String(v||'').split(',').map(x=>x.trim()).filter(Boolean)} join(v:any){return Array.isArray(v)?v.join(', '):''}
  uploaded(type:string){return (this.profile?.documents||[]).some((d:any)=>d.documentType===type)}
  chooseFile(type:string,event:Event){const file=(event.target as HTMLInputElement).files?.[0];if(file)this.pendingFiles[type]=file}
  async upload(type:string){this.error='';try{const result=await this.api.uploadStudentDocument(this.token,type,this.pendingFiles[type]);this.profile=result.data.profile;delete this.pendingFiles[type];this.message='Document uploaded successfully.';}catch(e){this.error=e instanceof Error?e.message:'Upload failed.'}}
  async next(){this.error='';this.message='';if(this.step===8){if(this.completion===100)this.completed.emit(this.profile);else this.error='Complete all six sections and upload at least one document before viewing offers.';return;}if(this.step===1||this.step===5){this.step++;return;}this.saving=true;try{let section='',payload:any={};if(this.step===0){section='personal';payload={firstName:this.form.firstName,lastName:this.form.lastName,profilePhoto:this.form.profilePhoto,dateOfBirth:this.form.dateOfBirth,gender:this.form.gender,nationality:this.form.nationality,country:this.form.country,state:this.form.state,city:this.form.city,address:this.form.address,phoneNumber:this.form.phoneNumber,passportStatus:this.form.passportStatus,passportNumber:this.form.passportNumber,shortBio:this.form.shortBio};}if(this.step===2){section='education';payload={studentType:this.form.studentType,graduationYear:Number(this.form.graduationYear),...(this.form.studentType==='SCHOOL'?{school:{schoolName:this.form.schoolName,educationBoard:this.form.educationBoard,currentGrade:this.form.currentGrade,marks10:this.form.marks10,marks11:this.form.marks11,marks12:this.form.marks12,subjects:this.split(this.form.subjects),academicAchievements:this.split(this.form.academicAchievements)}}:{college:{collegeName:this.form.collegeName,university:this.form.university,degree:this.form.degree,department:this.form.department,cgpa:Number(this.form.cgpa),currentSemester:this.form.currentSemester,numberOfBacklogs:Number(this.form.numberOfBacklogs),projects:this.split(this.form.projects),internships:this.split(this.form.internships),academicAchievements:this.split(this.form.academicAchievements)}})};}if(this.step===3){section='preferences';payload={preferredCountries:this.split(this.form.preferredCountries),preferredCourses:this.split(this.form.preferredCourses),degreeType:this.form.degreeType,preferredIntake:this.form.preferredIntake,budgetRange:this.form.budgetRange,scholarshipRequired:this.form.scholarshipRequired,accommodationRequired:this.form.accommodationRequired};}if(this.step===4){section='exams';payload={exams:this.form.exams};}if(this.step===6){section='skills';payload={technicalSkills:this.split(this.form.technicalSkills),softSkills:this.split(this.form.softSkills),languagesKnown:this.split(this.form.languagesKnown),certifications:this.split(this.form.certifications),hackathons:this.split(this.form.hackathons),competitions:this.split(this.form.competitions),volunteerExperience:this.split(this.form.volunteerExperience),leadershipExperience:this.split(this.form.leadershipExperience),portfolioUrl:this.form.portfolioUrl,linkedInUrl:this.form.linkedInUrl,githubUrl:this.form.githubUrl};}const result=await this.api.saveStudentProfileSection(this.token,section,payload);this.profile=result.data;this.message='Step saved. You can safely continue later.';this.step++;}catch(e){this.error=e instanceof Error?e.message:'This step could not be saved.';}finally{this.saving=false;}}
}
