// Indian universities list for the University / College Name field (Bachelor's & Master's Degree).
export const UNIVERSITY_OPTIONS: string[] = [
  "ICAR - Indian Council of Agricultural Research, Srinagar",
  "APJ Abdul Kalam Technological University",
  "AAFT University of Media and Arts",
  "Abhilashi University",
  "Acharya Nagarjuna University",
  "Acharya Narendra Deva University of Agriculture and Technology",
  "Acharya NG Ranga Agricultural University",
  "Adamas University",
  "Adesh University, Bathinda",
  "Adichunchanagiri University",
  "Adikavi Nannaya University",
  "Aditya University",
  "Agriculture University, Jodhpur, Jodhpur",
  "Agriculture University, Kota, Kota",
  "Ahmedabad University",
  "AIIMS, Rewari",
  "AIPH University",
  "AISECT University",
  "Akal University",
  "Aks University",
  "Al-Falah University",
  "Al-Karim University",
  "Alagappa University",
  "Aliah University",
  "Aligarh Muslim University",
  "Aligarh Muslim University, Malappuram",
  "Alipurduar University",
  "All India Institute of Hygiene and Public Health, Kolkata",
  "AIIMS, Bhubaneswar",
  "AIIMS, Delhi",
  "AIIMS, Jodhpur",
  "AIIMS, Rishikesh",
  "AIIMS, Awantipora",
  "AIIMS, Bathinda",
  "AIIMS, Bibinagar",
  "AIIMS, Deoghar",
  "AIIMS, Gorakhpur",
  "AIIMS, Guwahati",
  "AIIMS, Kalyani",
  "AIIMS, Nagpur",
  "AIIMS, Patna",
  "AIIMS, Raebareli",
  "AIIMS, Rajkot",
  "AIIMS, Vijaypur",
  "Alliance University",
  "Ambedkar University",
  "AMET University",
  "Amity University",
  "Amity University, Bengaluru",
  "Amity University, Jaipur",
  "Amity University, Haryana",
  "Amity University, Kolkata",
  "Amity University, Noida",
  "Amity University, Patna",
  "Amity University, Raipur",
  "Amrapali University",
  "Amrita Vishwa Vidyapeetham, Chennai",
  "Amrita Vishwa Vidyapeetham Haryana",
  "Amrita Vishwa Vidyapeetham, Amritapuri",
  "Amrita Vishwa Vidyapeetham, Kochi",
  "Anand Agricultural University",
  "Andhra Kesari University",
  "Andhra Pradesh Fisheries University",
  "Andhra University",
  "Anjaneya University",
  "Anna University",
  "Annamacharya University",
  "Annamalai University",
  "Anurag University",
  "Apeejay Stya University",
  "Apex Professional University",
  "APG Shimla University",
  "Arka Jain University",
  "Arni University",
  "Arunachal Law Academy",
  "Arunachal Pradesh University",
  "Arunachal University of Studies",
  "Aryabhatta Knowledge University",
  "ASBM University",
  "Ashoka University",
  "Asian International University",
  "Assam Agricultural University",
  "Assam Don Bosco University",
  "Assam Down Town University",
  "Assam Science and Technology University",
  "Assam Skill University",
  "Assam University",
  "Assam Veterinary and Fishery University",
  "Assam Women's University",
  "Atal Bihari Vajpayee Hindi Vishwavidyalaya",
  "IIITM Gwalior",
  "Atal Bihari Vajpayee Medical University",
  "Atal Bihari Vajpayee Vishwavidyalaya",
  "Atal Medical and research University",
  "Audisankara University",
  "Amity University, Gwalior",
  "Auniati University",
  "Auro University",
  "Avantika University",
  "Avinashilingam Institute for Home Science and Higher Education for Women",
  "Awadhesh Pratap Singh University",
  "Ayush & Health Sciences University, Chhattisgarh",
  "Azim Premji University",
  "BR Ambedkar Bihar University",
  "BS Abdur Rahman Crescent Institute of Science and Technology",
  "Baba Farid University of Health Sciences, Faridkot",
  "Baba Ghulam Shah Badshah University",
  "Baba Mast Nath University",
  "Baba Saheb Ambedkar Education University",
  "Babasaheb Bhimrao Ambedkar University",
  "Babu Banarasi Das University",
  "Babu Dinesh Singh University",
  "Baddi University of Emerging Sciences & Technologies",
  "Bagalkot University",
  "Bahra University",
  "Banaras Hindu University",
  "Banasthali Vidyapith, Vanasthali",
  "Banda University of Agriculture and Technology",
  "Bangalore University",
  "Bankura University",
  "Bareilly International University",
  "Barkatullah University",
  "Bengaluru City University",
  "Bengaluru Dr BR Ambedkar School of Economics University",
  "Bengaluru North University",
  "Bennett University",
  "Berhampur University",
  "Bhagat Phool Singh Mahila Vishwavidyalaya",
  "Bhagwant Global University",
  "Bhagwant University, Ajmer",
  "Bhakta Kavi Narsinh Mehta University",
  "Bharath Institute of Higher Education and Research",
  "Bharathiar University",
  "Bharathidasan Institute of Management",
  "Bharathidasan University",
  "Bharati Vidyapeeth, Pune",
  "Bharatiya Engineering Science and Technology Innovation University",
  "Bharti Vidyapeeth, Sonipat",
  "Bhatkhande Sanskriti Vishwavidyalaya",
  "Bhattadev University",
  "Bhupendra Narayan Mandal University",
  "Bidar University",
  "Bidhan Chandra Krishi Viswavidyalaya",
  "Bihar Agricultural University",
  "Bihar Animal Sciences University",
  "Bihar Engineering University",
  "Bihar University of Health Sciences",
  "Biju Patnaik National Steel Institute",
  "Biju Patnaik University of Technology",
  "Bikaner Technical University, Bikaner",
  "Binod Bihari Mahto Koylanchal University",
  "Bir Tikendrajit University",
  "Birangana Sati Sadhani Rajyik Vishwavidyalaya",
  "Birla Global University",
  "Birla Institute of Technology & Science, Pilani",
  "Birla Institute of Technology & Science, Pilani, Goa",
  "Birla Institute of Technology & Science, Pilani, Hyderabad",
  "Birla Institute of Technology, Mesra",
  "Birla Vishwakarma Mahavidyalaya",
  "Birsa Agricultural University",
  "Birsa Munda Tribal University",
  "Biswa Bangla Biswabidyalay",
  "BLDE University",
  "BML Munjal University",
  "BMS College for Women",
  "Bodoland University",
  "Bose Institute, Kolkata",
  "Brainware University",
  "Bundelkhand University",
  "CV Raman Global University",
  "Capital University",
  "Captain Williamson Sangma State University",
  "Career Point University, Hamirpur",
  "CCS Haryana Agricultural University",
  "Central Agricultural University",
  "Central Electro Chemical Research Institute, Karaikudi",
  "Central Electrochemical Research Institute",
  "Central Forensic Science Laboratory, Hyderabad",
  "Central Glass and Ceramic Research Institute, Kolkata",
  "Central Inland Fisheries Research Institute, Barrackpore",
  "Central Institute for Women in Agriculture, Bhubaneswar",
  "Central Institute of Brackish Water Aquaculture, Chennai",
  "Central Institute of Buddhist Studies",
  "Central Institute of Fisheries Education",
  "Central Institute of Freshwater Aquaculture, Cuttack",
  "Central Institute of Higher Tibetan Studies",
  "Central Institute of Himalayan Cultural Studies",
  "Central Institute of Medicinal and Aromatic Plants",
  "CIPET, Chandrapur",
  "CIPET, Chhatrapati Sambhaji Nagar",
  "CIPET, Chennai",
  "Central Institute of Psychiatry",
  "Central Institute of Technology, Kokrajhar",
  "Central Institute of Tool Design, Hyderabad",
  "Central Leather Research Institute, Adyar",
  "Central Mechanical Engineering Research Institute, Durgapur",
  "Central Power Research Institute, Telangana",
  "Central Research Institute for Dryland Agriculture (CRIDA), ICAR, Hyderabad",
  "Central Research Institute for Jute and Allied Fibers, Barrackpore",
  "Central Research Institute of Yoga & Naturopathy (CRIYN, Jhajjar)",
  "Central Sanskrit University (CSU), Guruvayoor",
  "Central Sanskrit University (Ekalavya Campus)",
  "Central Sanskrit University (Shri Sadashiv Campus)",
  "Central Sericultural Research and Training Institute, Berhampore",
  "Central Tobacco Research Institute",
  "Central Tool Room and Training Centre, Bhubaneswar",
  "Central Tribal University of Andhra Pradesh",
  "Central Tuber Crops Research Institute - Regional Centre, Bhubaneswar",
  "Central University of Andhra Pradesh",
  "Central University of Gujarat",
  "Central University of Haryana",
  "Central University of Himachal Pradesh",
  "Central University of Jammu",
  "Central University of Jharkhand",
  "Central University of Karnataka",
  "Central University of Kashmir",
  "Central University of Kerala",
  "Central University of Odisha",
  "Central University of Punjab",
  "Central University of Rajasthan",
  "Central University of South Bihar",
  "Central University of Tamil Nadu",
  "Centre for Cellular and Molecular Biology (CCMB), Hyderabad",
  "Centre for Development of Advanced Computing",
  "Centre for DNA Fingerprinting and Diagnostics (CDFD), Hyderabad",
  "Centre for Economic and Social Studies (CESS), Hyderabad",
  "Centre for High Energy Systems and Sciences (CHESS), Hyderabad",
  "Centurion University of Technology & Management",
  "Centurion University of Technology and Management",
  "CEPT University",
  "Chaitanya University",
  "Chanakya National Law University",
  "Chandigarh University, Mohali",
  "Chandra Shekhar Azad University of Agriculture & Technology",
  "Charotar University of Science and Technology",
  "Chaudhary Bansi Lal University",
  "Chaudhary Charan Singh University",
  "Chaudhary Devi Lal University",
  "Chaudhary Ranbir Singh University",
  "Chaudhary Sarwan Kumar Himachal Pradesh Krishi Vishvavidyalaya",
  "Chennai Mathematical Institute",
  "Chettinad Academy of Research and Education",
  "Chhatrapati Shahu Ji Maharaj University",
  "Chhattisgarh Kamdhenu Vishwavidyalaya",
  "Chhattisgarh Swami Vivekanand Technical University",
  "Children's Research University",
  "Chinmaya Vishwavidyapeeth",
  "Chitkara University, Himachal Pradesh",
  "Chitkara University, Punjab",
  "Christ University",
  "Cluster University",
  "Cluster University of Jammu",
  "Cluster University of Srinagar",
  "CMJ University",
  "CMR University",
  "Cochin University of Science and Technology",
  "College of Engineering Roorkee",
  "Cooch Behar Panchanan Barma University",
  "Cotton University",
  "CR Rao Advanced Institute of Mathematics, Statistics and Computer Science",
  "CT University, Ludhiana",
  "CU Shah University",
  "DY Patil Education Society",
  "Dakshin Dinajpur University",
  "Damodaram Sanjivayya National Law University",
  "Darjeeling Hills University",
  "Datta Meghe Institute of Medical Sciences",
  "DAV University",
  "Davangere University",
  "Dayalbagh Educational Institute",
  "Dayananda Sagar University",
  "DBS Global University",
  "Deccan College Post-Graduate and Research Institute",
  "Deen Dayal Upadhyay Gorakhpur University",
  "Deenbandhu Chhotu Ram University of Science and Technology",
  "Defence Institute of Advanced Technology",
  "Delhi Pharmaceutical Sciences and Research University",
  "Delhi Skill and Entrepreneurship University",
  "Delhi Technological University",
  "Delhi University",
  "Desh Bhagat University, Mandi Gobindgarh",
  "Dev Bhoomi Uttarakhand University",
  "Dev Sanskriti Vishwavidyalaya",
  "Devi Ahilya University",
  "Dhamma Dipa International Buddhist University",
  "Dhanalakshmi Srinivasan University",
  "Dhanamanjuri University",
  "Dharamsinh Desai University",
  "Dharanidhar University",
  "Dhirubhai Ambani Institute of Information and Communication Technology",
  "Diamond Harbour Women's University",
  "Dibrugarh University",
  "DIT University",
  "Doon University",
  "Dr Abdul Haq Urdu University",
  "Dr Babasaheb Ambedkar Open University",
  "Dr BR Ambedkar University, Srikakulam",
  "Dr CV Raman University, Chhattisgarh",
  "Dr CV Raman University, Bihar",
  "Dr NTR University of Health Sciences",
  "Dr Rajendra Prasad Central Agricultural University",
  "Dr Shyama Prasad Mukherjee International Institute of Information Technology",
  "Dr YSR Architecture and Fine Arts University",
  "Dr YSR Horticultural University",
  "Dr. APJ Abdul Kalam Technical University",
  "Dr BR Ambedkar National Institute of Technology, Jalandhar",
  "Dr BR Ambedkar Open University, Hyderabad",
  "Dr BR Ambedkar University, Agra",
  "Dr Babasaheb Ambedkar Marathwada University",
  "Dr Babasaheb Ambedkar Technological University",
  "Dr Balasaheb Sawant Konkan Krishi Vidyapeeth",
  "Dr Bhimrao Ambedkar Law University, Jaipur",
  "Dr DY Patil Vidyapeeth",
  "Dr Hari Singh Gour University",
  "Dr KN Modi University",
  "Dr MGR Educational and Research Institute",
  "Dr Marri Channa Reddy Human Resource Development Institute of Telangana",
  "Dr Panjabrao Deshmukh Krishi Vidyapeeth",
  "Dr Rajendra Prasad Central Agriculture University",
  "Dr Ram Manohar Lohia Avadh University",
  "Dr Ram Manohar Lohia Institute of Medical Sciences",
  "Dr Ram Manohar Lohiya National Law University",
  "Dr Shyama Prasad Mukherjee University",
  "Dr Yashwant Singh Parmar University of Horticulture and Forestry",
  "Dravidian University",
  "DRIEMS University",
  "DSM National Rehabilitation University",
  "Durga Soren University",
  "DY Patil Agriculture & Technical University",
  "EdTech Skill University",
  "English and Foreign Languages University, Hyderabad",
  "Era University",
  "Eternal University",
  "Ethics University",
  "FS University",
  "Fakir Mohan University",
  "Footwear Design and Development Institute, Rohtak",
  "Footwear Design and Development Institute, Hyderabad",
  "Footwear Design and Development Institute, Chennai",
  "Forest College and Research Institute (FCRI), Hyderabad",
  "Forest Research Institute, Dehradun",
  "GB Pant University of Agriculture and Technology",
  "GH Raisoni University",
  "Galgotias University",
  "Gandhi Institute of Technology and Management (GITAM), Visakhapatnam",
  "Gandhi Institute of Technology and Management (GITAM), Hyderabad",
  "Gandhinagar University",
  "Gangadhar Meher University",
  "Ganpat University",
  "Garden City University",
  "Gati Shakti Vishwavidyalaya",
  "Gauhati University",
  "Gautam Buddha University",
  "GD Goenka University",
  "Geeta University",
  "Ghani Khan Choudhury Institute of Engineering & Technology",
  "GIET University",
  "Girijananda Chowdhury University",
  "GLA University",
  "GLS University",
  "GNA University, Phagwara",
  "Goa Institute of Management",
  "Goa University",
  "Godavari Global University",
  "Gokhale Institute of Politics and Economics",
  "Gondwana University",
  "Gopal Narayan Singh University",
  "Govind Guru Tribal University",
  "Graphic Era Hill University",
  "Graphic Era University",
  "Great Lake International University",
  "Gujarat Ayurved University",
  "Gujarat Biotechnology University",
  "Gujarat Technological University",
  "Gujarat University",
  "Gujarat Vidyapith",
  "Gulbarga University",
  "Guru Angad Dev Veterinary and Animal Sciences University",
  "Guru Ghasidas University",
  "Guru Gobind Singh Indraprastha University",
  "Guru Jambheshwar University of Science and Technology",
  "Guru Kashi University",
  "Guru Nanak Dev University",
  "Guru Ravidas Ayurved University",
  "Gurucharan University",
  "Gurugram University",
  "Gurukula Kangri Vishwavidyalaya",
  "Gyan Vihar University, Jaipur",
  "HNB Garhwal University",
  "HNB Uttarakhand Medical Education University",
  "Harcourt Butler Technical University",
  "Harichand Guruchand University",
  "Haridev Joshi University of Journalism and Mass Communication, Jaipur",
  "Haridwar University",
  "Haryana Institute of Civil Aviation",
  "Haryana Vishwakarma Skill University",
  "Hemchand Yadav Vishwavidyalaya",
  "Hemchandracharya North Gujarat University",
  "Hidayatullah National Law University",
  "Himachal Pradesh Technical University",
  "Himachal Pradesh University",
  "Himalayan Group of Professional Institutions",
  "Himalayan University",
  "Hindi University",
  "Hindustan Institute of Technology and Science",
  "Holkar Science College,Indore",
  "Homi Bhabha National Institute",
  "ICAR Central Institute of Fisheries Education, Rohtak",
  "ICAR - Indian Agricultural Research Institute",
  "ICFAI University",
  "ICFAI University, Chumoukedima",
  "ICFAI University, Meghalaya",
  "ICFAI University, Mizoram, Aizawl",
  "ICFAI University, Raipur",
  "ICFAI University, Sikkim",
  "ICFAI University, Tripura",
  "IEC University",
  "IFTM University",
  "IIIT, Bhubaneswar",
  "IILM University",
  "IILM University Greater Noida",
  "IIMT University",
  "IIS University, Jaipur",
  "IIT, Delhi Sonipat Campus",
  "IIT, Dharward",
  "IK Gujral Punjab Technical University, Jalandhar",
  "IMS Unison University",
  "India International University of Legal Education and Research",
  "Indian Association for the Cultivation of Science",
  "Indian Centre for Space Physics, Kolkata",
  "Indian Culinary Institute, Tirupati",
  "Indian Institute of Chemical Biology, Kolkata",
  "Indian Institute of Chemical Technology (IICT), Hyderabad",
  "Indian Institute of Engineering Science and Technology, Shibpur",
  "Indian Institute of Food Processing Technology",
  "Indian Institute of Foreign Trade, Kakinada",
  "Indian Institute of Foreign Trade, New Delhi",
  "Indian Institute of Forest Management, Bhopal",
  "Indian Institute of Handloom Technology, Bargarh",
  "Indian Institute of Handloom Technology, Salem",
  "Indian Institute of Industry Interaction Education & Research (IIIER Chennai)",
  "Indian Institute of Information Technology Design & Manufacturing Kancheepuram",
  "IIIT, Raichur",
  "IIIT, Tiruchirappalli",
  "IIIT, Una",
  "IIIT, Agartala",
  "IIIT, Allahabad",
  "IIIT, Bhagalpur",
  "Indian Institute of Information Technology, Design and Manufacturing, Jabalpur",
  "IIIT, Guwahati",
  "IIIT, Kalyani",
  "IIIT, Kota",
  "IIIT, Lucknow",
  "IIIT, Manipur",
  "IIIT, Nagpur",
  "IIIT, Pune",
  "IIIT, Ranchi",
  "IIIT, Sonepat",
  "IIIT, Sri City",
  "IIIT, Surat",
  "IIIT, Vadodara",
  "Indian Institute of Integrative Medicine (IIIM), Srinagar",
  "IIM, Kozhikode",
  "IIM, Sambalpur",
  "IIM, Amritsar",
  "IIM, Bangalore",
  "IIM, Calcutta",
  "IIM, Guwahati",
  "IIM, Indore",
  "IIM, Jammu",
  "IIM, Kashipur",
  "IIM, Ranchi",
  "IIM, Shillong",
  "IIM, Tiruchirappalli",
  "IIM, Udaipur",
  "IIM, Ahmedabad",
  "IIM, Bodh Gaya",
  "IIM, Lucknow",
  "IIM, Mumbai",
  "IIM, Nagpur",
  "IIM, Rohtak",
  "IIM, Visakhapatnam",
  "Indian Institute of Mass Communication, Delhi",
  "Indian Institute of Mass Communication, Jammu",
  "Indian Institute of Mass Communication, Kottayam",
  "Indian Institute of Millets Research",
  "Indian Institute of Oilseeds Research",
  "Indian Institute of Packaging, Chennai",
  "Indian Institute of Packaging, Hyderabad",
  "Indian Institute of Petroleum and Energy",
  "Indian Institute of Public Health, Bhubaneswar",
  "IISc, Bengaluru",
  "IISER, Thiruvananthapuram",
  "IISER, Tirupati",
  "IISER, Brahmapur",
  "IISER, Bhopal",
  "IISER, Kolkata",
  "IISER, Mohali",
  "IISER, Pune",
  "Indian Institute of Space Science and Technology",
  "Indian Institute of Teacher Education",
  "IIT, Varanasi",
  "IIT, Bhubaneswar",
  "IIT, Delhi",
  "IIT, Dharwad",
  "IIT, Gandhinagar",
  "IIT, Guwahati",
  "IIT, Hyderabad",
  "IIT, Indore",
  "IIT, Jammu",
  "IIT, Jodhpur",
  "IIT, Kharagpur",
  "IIT, Madras",
  "IIT, Mandi",
  "IIT, Roorkee",
  "IIT, Palakkad",
  "IIT, Mumbai",
  "IIT, Goa",
  "IIT, Kanpur",
  "IIT, Patna",
  "IIT, Ropar",
  "IIT, Tirupati",
  "Indian Institute of Tourism and Travel Management, Noida",
  "Indian Institute of Tourism and Travel Management, Nellore",
  "Indian Institute of Tourism and Travel Management, Bhubaneswar",
  "Indian Institute of Tourism and Travel Management, Gwalior",
  "Indian Institute of Water Management, Bhubaneswar",
  "Indian Law Institute",
  "Indian Maritime University, Mumbai",
  "Indian Maritime University, Kochi",
  "Indian Maritime University Kolkata",
  "Indian Maritime University, Chennai",
  "Indian Maritime University, Visakhapatnam",
  "Indian National Centre for Ocean Information Services, Hyderabad",
  "ISB, Hyderabad",
  "ISB, Mohali",
  "Indian Statistical Institute, Kolkata",
  "Indian Statistical Institute Tezpur",
  "Indian Veterinary Research Institute",
  "Indira Gandhi Delhi Technical University for Women",
  "Indira Gandhi Institute of Development Research",
  "Indira Gandhi Krishi Vishwavidyalaya",
  "Indira Gandhi National Open University (IGNOU)",
  "Indira Gandhi National Tribal University",
  "Indira Gandhi Technological and Medical Sciences University",
  "Indira Gandhi University",
  "Indira Kala Sangeet Vishwavidyalaya",
  "IIIT, Delhi",
  "Indus International University",
  "Indus University",
  "Institute for Development and Research in Banking Technology",
  "Institute For Excellence In Higher Education",
  "Institute of Advanced Studies in Education",
  "Institute of Chemical Technology, Mumbai",
  "Institute of Chemical Technology, Chennai",
  "Institute of Chemical Technology, Bhubaneswar",
  "Institute of Forest Biodiversity",
  "Institute of Genetics and Hospital for Genetic Diseases",
  "Institute Of Hotel Management Catering Technology And Applied Nutrition, Bhubaneswar",
  "Institute of Hotel Management, Shillong",
  "Institute of Infrastructure Technology Research and Management",
  "Institute of Life Sciences, Bhubaneswar",
  "Institute of Liver and Biliary Sciences (ILBS)",
  "Institute of Mathematical Sciences, Chennai",
  "Institute of Mathematics and Applications, Bhubaneswar",
  "Institute of Minerals and Materials Technology, Bhubaneswar",
  "Institute of Physics, Bhubaneswar",
  "Institute of Public Enterprise",
  "Institute of Rural Management",
  "Institute of Teaching and Research in Ayurveda, Jamnagar",
  "Institute of Trans-Disciplinary Health Sciences and Technology",
  "Integral University",
  "International Crops Research Institute for the Semi-Arid Tropics (ICRISAT), Hyderabad",
  "International Institute for Population Sciences",
  "IIIT, Hyderabad",
  "IIIT, Bangalore",
  "IIIT, Naya Raipur",
  "International Institute of Management and Technical Studies, Ahmedabad",
  "International Management Institute, Kolkata",
  "International School of Engineering",
  "Invertis University",
  "ISBM University",
  "Indian Statistical Institute, Delhi",
  "Islamic University of Science and Technology (IUST)",
  "ITM University",
  "JS University",
  "Jabalpur Engineering College",
  "Jadavpur University",
  "Jagadguru Kripalu University",
  "Jagadguru Ramanandacharya Rajasthan Sanskrit University, Jaipur",
  "Jagadguru Rambhadracharya Handicapped University",
  "Jagadguru Sri Shivarathreeshwara University",
  "Jagannath University",
  "Jagannath Barooah University",
  "Jagannath University, Jaipur",
  "Jagat Guru Nanak Dev Punjab State Open University, Patiala",
  "Jagran Lakecity University",
  "Jai Narain Vyas University, Jodhpur",
  "Jai Prakash University",
  "Jain University, Bengaluru",
  "Jain Vishva Bharati University, Ladnu",
  "Jaipur National University, Jaipur",
  "Jamia Hamdard University",
  "Jamia Millia Islamia",
  "Jammu and Kashmir State Forest Research Institute (J&KSFRI)",
  "Jamshedpur Women's University",
  "Jananayak Chandrashekhar University",
  "Janardan Rai Nagar Rajasthan Vidyapeeth University, Udaipur",
  "Jawaharlal Nehru Agricultural University",
  "Jawaharlal Nehru Architecture and Fine Arts University, Hyderabad",
  "Jawaharlal Nehru Centre for Advanced Scientific Research",
  "Jawaharlal Nehru Technological University, Anantapur",
  "Jawaharlal Nehru Technological University - Gurajada, Vizianagaram",
  "Jawaharlal Nehru Technological University, Hyderabad",
  "Jawaharlal Nehru Technological University, Kakinada",
  "Jawaharlal Nehru Technological University, Ramagundam",
  "Jawaharlal Nehru Technological University, Sultanpur",
  "Jawaharlal Nehru University",
  "Jaypee Institute of Information Technology",
  "Jaypee University of Engineering and Technology",
  "Jaypee University of Information Technology",
  "Jaypee University, Anoopshahr",
  "JC Bose University of Science and Technology",
  "JECRC University, Jaipur",
  "Jeppiaar University",
  "Jharkhand Rai University",
  "Jharkhand Raksha Shakti University",
  "Jharkhand State Open University",
  "Jharkhand University of Technology",
  "Jigyasa University",
  "JIS University",
  "Jiwaji University",
  "JK Lakshmipat University, Jaipur",
  "Jodhpur National University, Jodhpur",
  "Joy University, Tamilnadu",
  "JSS Academy of Higher Education and Research, Mysuru",
  "Junagadh Agricultural University",
  "Jyoti Nivas College",
  "KLE Academy of Higher Education and Research",
  "KM University",
  "Kadi Sarva Vishwavidyalaya",
  "Kakatiya University",
  "Kalasalingam Academy of Research and Education",
  "Kalinga Institute of Industrial Technology",
  "Kalinga Institute of Social Sciences",
  "Kalinga University",
  "Kaloji Narayana Rao University of Health Sciences",
  "Kamdhenu University",
  "Kameshwar Singh Darbhanga Sanskrit University",
  "Kannada University",
  "Kannur University",
  "Kanyashree University",
  "Karnatak University",
  "Karnataka Folklore University",
  "Karnataka Samskrit University",
  "Karnataka State Dr. Gangubhai Hangal Music and Performing Arts University",
  "Karnataka State Law University",
  "Karnataka State Open University (KSOU)",
  "Karnataka State Rural Development and Panchayat Raj University",
  "Karnataka State Women's University",
  "Karnataka Veterinary, Animal and Fisheries Sciences University",
  "Karpagam Academy of Higher Education",
  "Karunya Institute of Technology and Sciences",
  "Kaushal Vidya Entrepreneurship , Digital and Skill University",
  "Kaushalya Skill University",
  "Kavayitri Bahinabai Chaudhari North Maharashtra University",
  "Kavikulguru Kalidas Sanskrit University",
  "Kazi Nazrul University",
  "Kaziranga University",
  "Kerala Agricultural University",
  "Kerala Kalamandalam",
  "Kerala University of Digital Sciences, Innovation and Technology",
  "Kerala University of Fisheries and Ocean Studies",
  "Kerala University of Health Sciences",
  "Kerala Veterinary and Animal Sciences University",
  "Khaja Bandanawaz University",
  "Khallikote Unitary University",
  "Khangchendzonga State University",
  "Khongnangthaba University",
  "Khwaja Moinuddin Chishti Language University",
  "King George's Medical University",
  "KK Modi University",
  "KK University",
  "KL University",
  "KLE Technological University",
  "Kodagu University",
  "Kokrajhar University",
  "Kolhan University",
  "KR Mangalam University",
  "Krantiguru Shyamji Krishna Verma Kachchh University",
  "KREA University",
  "Krishna Institute of Medical Sciences",
  "Krishna Kanta Handique State Open University",
  "Krishna University",
  "Krishnaguru Adhyatmik Vishvavidyalaya",
  "Kristu Jayanti University",
  "Kumar Bhaskar Varma Sanskrit and Ancient Studies University",
  "Kumaun University",
  "Kurukshetra University",
  "Kushabhau Thakre Patrakarita Avam Jansanchar Vishwavidyalaya",
  "Kuvempu University",
  "Lakshmibai National University of Physical Education",
  "Lala Lajpat Rai University of Veterinary and Animal Sciences",
  "Lalit Narayan Mithila University",
  "Lingaya's University",
  "LNCT University",
  "LNCT Vidhyapeeth University",
  "LNM Institute of Information Technology, Jaipur",
  "Lovely Professional University",
  "MS Ramaiah College of Arts, Science, and Commerce",
  "MS Ramaiah University of Applied Sciences",
  "MJP Rohilkhand University",
  "MBM University",
  "Maa Manikeshwari University",
  "Maa Pateswari University",
  "Maa Shakumbhari University",
  "Maa Vindhyavasini University",
  "Madan Mohan Malaviya University of Technology",
  "Madanapalle Institute of Technology and Science",
  "Madhabdev University",
  "Madhusudan Law University",
  "Madhya Pradesh Bhoj Open University",
  "Madhya Pradesh Medical Science University",
  "Madhyanchal Professional University",
  "Madras Institute of Development Studies",
  "Madurai Kamaraj University",
  "Magadh University",
  "Mahakaushal University Jabalpur",
  "Mahapurusha Srimanta Sankaradeva Viswavidyalaya",
  "Maharaja Agrasen Himalayan Garhwal University",
  "Maharaja Agrasen University",
  "Maharaja Bir Bikram University",
  "Maharaja Chhatrasal Bundelkhand University",
  "Maharaja Ganga Singh University, Bikaner",
  "Maharaja Krishnakumarsinhji Bhavnagar University",
  "Maharaja Ranjit Singh State Technical University, Bathinda",
  "Maharaja Sayajirao University of Baroda",
  "Maharaja Sriram Chandra Bhanja Deo University",
  "Maharaja Surajmal Brij University, Bharatpur, Bharatpur",
  "Maharana Pratap Horticultural University, Karnal",
  "Maharana Pratap University of Agriculture and Technology, Udaipur",
  "Maharani Lakshmi Ammanni College for Women",
  "Maharashtra Animal and Fishery Sciences University",
  "Maharashtra National Law University, Aurangabad",
  "Maharashtra National Law University, Mumbai",
  "Maharashtra National Law University, Nagpur",
  "Maharashtra State Board of Technical Education",
  "Maharashtra University of Health Sciences",
  "Maharishi Balmiki Sanskrit University, Kaithal",
  "Maharishi Mahesh Yogi Vedic Vishwavidyalaya",
  "Maharishi Markandeshwar University, Mullana",
  "Maharishi Markandeshwar University, Solan",
  "Maharishi Panini Sanskrit Evam Vedic Vishwavidyalaya",
  "Maharishi University of Information Technology",
  "Maharishi University of Management and Technology",
  "Maharshi Dayanand Saraswati University, Ajmer",
  "Maharshi Dayanand University",
  "Mahatma Gandhi Antarrashtriya Hindi Vishwavidyalaya, Wardha",
  "Mahatma Gandhi Central University",
  "Mahatma Gandhi Chitrakoot Gramoday University",
  "Mahatma Gandhi Kashi Vidyapeeth",
  "Mahatma Gandhi Udyanikee and Vanikee Vishwavidyalaya, Patan Durg",
  "Mahatma Gandhi University, Kerala",
  "Mahatma Gandhi University, Meghalaya",
  "Mahatma Gandhi University, Nalgonda",
  "Mahatma Gandhi University, West Bengal",
  "Mahatma Phule Krishi Vidyapeeth",
  "Mahayogi Gorakhnath University",
  "Mahindra University, Hyderabad",
  "Major SD Singh University",
  "Majuli University of Culture",
  "Makhanlal Chaturvedi National University of Journalism and Communication",
  "Malaviya National Institute of Technology, Jaipur",
  "Management and Information Technology University",
  "Manav Bharti University",
  "Manav Rachna International Institute of Research and Studies",
  "Manav Rachna University",
  "Mandsaur University",
  "Mandya University",
  "Mangalayatan University",
  "Mangalore University",
  "Manipal Academy of Higher Education (MAHE)",
  "Manipal University Jaipur",
  "Manipur Institute of Technology",
  "Manipur International University",
  "Manipur Technical University",
  "Manipur University",
  "Manipur University of Culture",
  "Manonmaniam Sundaranar University",
  "Mansarovar Global University",
  "Martin Luther Christian University",
  "Marwadi University, Rajkot",
  "Mata Gujri University",
  "MATS University",
  "Maulana Abul Kalam Azad University of Technology",
  "Maulana Azad National Institute of Technology",
  "Maulana Azad National Urdu University",
  "Maulana Azad University, Jodhpur",
  "Maulana Mazharul Haque Arabic and Persian University",
  "Maya Devi University",
  "Medhavi Skills University, Sikkim",
  "MedTech Institute for Legal Studies",
  "Meenakshi Academy of Higher Education and Research",
  "MES College of Arts, Commerce and Science",
  "Mewar University, Chittorgarh",
  "MG University, Kottayam",
  "MGM Institute of Health Sciences",
  "MICA, Ahmedabad",
  "Mind Power University",
  "MIT University, Meghalaya",
  "MIT Vishwaprayag University",
  "Mizoram State University (MZSU)",
  "Mizoram University (MZU), Aizawl",
  "Mody University, Laxmangarh, Sikar",
  "Mohammad Ali Jauhar University",
  "Mohan Babu University",
  "Mohanlal Sukhadia University, Udaipur",
  "Monad University",
  "Mother Teresa Women's University",
  "Motherhood University",
  "Motilal Nehru National Institute of Technology, Allahabad",
  "Mount Carmel College",
  "Munger University",
  "Murshidabad Maharaja Krishnanath University",
  "MVN University",
  "Nagaland University",
  "Nagaon University",
  "Nalanda Open University",
  "Nalanda University",
  "Nalsar University of Law",
  "Nanaji Deshmukh Veterinary Science University",
  "Narsee Monjee Institute of Management Studies",
  "National Academy of Agricultural Research Management (NAARM), ICAR, Hyderabad",
  "National Academy of Construction, Hyderabad",
  "National Academy of Customs Indirect Taxes and Narcotics",
  "National Animal Resource Facility for Biomedical Research",
  "National Balloon Facility",
  "National Brain Research Centre (NBRC, Manesar)",
  "National Bureau of Plant Genetic Resources (NBPGR), ICAR, Hyderabad",
  "National Dairy Research Institute (NDRI, Karnal)",
  "National Environmental Engineering Research Institute (NEER), Hyderabad",
  "National Fire Service College, Nagpur",
  "National Forensic Sciences University, Gujarat",
  "National Forensic Sciences University, Tripura",
  "National Forensic Sciences University, Guwahati",
  "National Geophysical Research Institute (NGRI), Hyderabad",
  "National Institute for Research in Bacterial Infections, Kolkata",
  "National Institute of Advanced Manufacturing Technology",
  "National Institute of Agricultural Extension Management (MANAGE), Hyderabad",
  "National Institute of Animal Biotechnology",
  "National Institute of Ayurveda, Panchkula",
  "National Institute of Biomedical Genomics, Kalyani",
  "National Institute of Design, Ahmedabad",
  "National Institute of Design, Amaravati",
  "National Institute of Design, Assam",
  "National Institute of Design, Kurukshetra",
  "National Institute Of Education Development Society & Sports Council",
  "National Institute of Educational Planning and Administration",
  "NIELIT Imphal",
  "NIELIT Churachandpur",
  "NIELIT Senapati",
  "NIELIT Itanagar",
  "NIELIT Pasighat",
  "NIELIT Tezu",
  "NIELIT Kohima",
  "NIELIT Chuchuyimlang",
  "NIELIT Shillong",
  "NIELIT Tura",
  "NIELIT Majuli",
  "NIELIT Bhubaneswar",
  "NIELIT Kolkata",
  "NIELIT Patna",
  "NIELIT Ranchi",
  "NIELIT Calicut",
  "NIELIT Chennai",
  "NIELIT Hyderabad",
  "NIELIT Tirupati",
  "NIELIT Ajmer",
  "NIELIT Aurangabad",
  "NIELIT Daman",
  "NIELIT Chandigarh",
  "NIELIT Delhi",
  "NIELIT Gorakhpur",
  "NIELIT Lucknow",
  "NIELIT Haridwar",
  "NIELIT Kurukshetra",
  "NIELIT Pali",
  "NIELIT Mandi",
  "NIELIT Shimla",
  "NIELIT Srinagar",
  "NIELIT Jammu",
  "NIELIT Leh",
  "NIELIT Agartala",
  "NIELIT Aizawl",
  "NIELIT Lunglei",
  "NIELIT Gangtok",
  "NIELIT Guwahati",
  "NIELIT Dibrugarh",
  "NIELIT Jorhat",
  "NIELIT Kokrajhar",
  "NIELIT Silchar",
  "NIELIT Tezpur",
  "NIFT, Delhi",
  "NIFT, Chennai",
  "NIFT, Gandhinagar",
  "NIFT, Hyderabad",
  "NIFT, Kolkata",
  "NIFT, Navi Mumbai",
  "NIFT, Bengaluru",
  "NIFT, Raebareli",
  "NIFT, Bhopal",
  "NIFT, Kannur",
  "NIFT, Shillong",
  "NIFT, Patna",
  "NIFT, Kangra",
  "NIFT, Bhubaneswar",
  "NIFT, Jodhpur",
  "NIFT, Srinagar",
  "NIFT, Panchkula",
  "NIFT, Daman",
  "NIFT, Varanasi",
  "National Institute of Food Technology Entrepreneurship and Management (NIFTEM, Sonipat)",
  "National Institute of Foot and Mouth Disease, Bhubaneswar",
  "National Institute of Indian Medical Heritage",
  "National Institute of Mental Health and Neurosciences",
  "National Institute of Micro, Small and Medium Enterprises, Hyderabad",
  "National Institute of Natural Fibre Engineering and Technology, Kolkata",
  "National Institute of Nutrition (NIN), Tarnaka, Hyderabad",
  "National Institute of Ocean Technology",
  "National Institute of Oceanography",
  "National Institute of Pharmaceutical Education and Research, Mohali",
  "National Institute of Pharmaceutical Education and Research, Ahmedabad",
  "National Institute of Pharmaceutical Education and Research, Guwahati",
  "National Institute of Pharmaceutical Education and Research, Hajipur",
  "National Institute of Pharmaceutical Education and Research, Hyderabad",
  "National Institute of Pharmaceutical Education and Research, Kolkata",
  "National Institute of Pharmaceutical Education and Research, Raebareli",
  "National Institute of Plant Health Management (NIPHM), Hyderabad",
  "National Institute of Rural Development (NIRD)",
  "National Institute of Science Education and Research (NISER), Bhubaneswar",
  "National Institute of Science Education and Research, Jatani",
  "National Institute of Technical Teacher's Training and Research",
  "National Institute of Technical Teachers' Training and Research, Kolkata",
  "NIT, Surathkal",
  "NIT, Warangal",
  "NIT, Bhopal",
  "NIT, Shibpur",
  "NIT, Nagpur",
  "NIT, Durgapur",
  "NIT, Jamshedpur",
  "NIT, Srinagar",
  "NIT, Prayagraj",
  "NIT, Surat",
  "NIT, Kozhikode",
  "NIT, Rourkela",
  "NIT, Jaipur",
  "NIT, Kurukshetra",
  "NIT, Tiruchirappalli",
  "NIT, Hamirpur",
  "NIT, Jalandhar",
  "NIT, Patna",
  "NIT, Raipur",
  "NIT, Agartala",
  "NIT, Yupia",
  "NIT, New Delhi",
  "NIT, Cuncolim",
  "NIT, Imphal",
  "NIT, Shillong",
  "NIT, Aizawl",
  "NIT, Chumoukedima",
  "NIT, Karaikal",
  "NIT, Ravangla",
  "NIT, Tadepalligudem",
  "National Institute of Tourism and Hospitality Management",
  "National Law Institute University",
  "National Law School of India University",
  "National Law University, Tripura",
  "National law University",
  "National Law University and Judicial Academy, Assam",
  "National Law University Odisha",
  "National Law University, Delhi",
  "National Law University, Jodhpur",
  "National Law University, Sonipat",
  "National Museum Institute (NMI)",
  "National Power Training Institute, Nagpur",
  "National Research Centre on Meat (NRCM), ICAR, Hyderabad",
  "National Rice Research Institute, Cuttack",
  "National Sanskrit University",
  "National School of Drama",
  "National Sports University",
  "National University of Advanced Legal Studies (NUALS)",
  "National University of Study and Research in Law",
  "Nava Nalanda Mahavihara",
  "Navsari Agricultural University",
  "Nehru Gram Bharati",
  "Netaji Subhas Open University",
  "Netaji Subhas University",
  "Netaji Subhas University of Technology",
  "NIILM University, Kaithal",
  "NIIT University, Neemrana",
  "Nilamber-Pitamber University",
  "NIMS University, Jaipur",
  "NIPER Hyderabad",
  "Nirma University of Science and Technology",
  "NIST University",
  "NITTE University, Mangalore",
  "Nizam's Institute of Medical Sciences",
  "NMKRV College for Women",
  "NMV University",
  "Noida International University",
  "Noorul Islam Centre for Higher Education",
  "North East Christian University, Medziphema",
  "North East Frontier Technical University (NEFTU)",
  "North East Homeopathic Medical College",
  "North Eastern Hill University, Shillong",
  "North Eastern Regional Institute of Science and Technology",
  "North Lakhimpur University",
  "Northeast Adventist University",
  "Odia University",
  "Odisha State Open University",
  "Odisha University of Agriculture and Technology",
  "Odisha University of Health Sciences",
  "Odisha University of Technology and Research",
  "Om Sterling Global University",
  "OP Jindal Global University",
  "OP Jindal University",
  "OPJS University, Rajasthan",
  "Oriental University",
  "Osmania University",
  "PP Savani University",
  "PV Narasimha Rao Telangana Veterinary University",
  "Pacific Academy of Higher Education and Research Udaipur, Udaipur",
  "Palamuru University",
  "Pandit Bhagwat Dayal Sharma University of Health Sciences",
  "Pandit Deen Dayal Upadhayaya University of Health Sciences",
  "Pandit Deendayal Energy University (PDEU)",
  "Pandit Deendayal Upadhyaya Shekhawati University, Sikar",
  "Pandit Ravishankar Shukla University",
  "Pandit Sundarlal Sharma (Open) University",
  "Panjab University",
  "Panjab University, Chandigarh",
  "Parul University",
  "Patel College of Science & Technology",
  "Patliputra University",
  "Patna University",
  "PDM University",
  "People's University",
  "Periyar Maniammai Institute of Science & Technology",
  "Periyar University",
  "PES University",
  "Phonics University",
  "Pillai University",
  "PK University",
  "Pondicherry University",
  "PRIST University",
  "Poornima University, Jaipur",
  "Postgraduate Institute of Medical Education and Research",
  "Pragjyotishpur University",
  "Pragyan International University",
  "Pravara Institute of Medical Sciences",
  "Presidency University",
  "Prof Rajendra Singh (Rajju Bhaiya) University",
  "Professor Jayashankar Telangana State Agricultural University",
  "Puducherry Technological University",
  "Punjab Agricultural University, Ludhiana",
  "Punjab Engineering College",
  "Punjab Sports University, Patiala",
  "Punjabi University Guru Kashi Campus, Talwandi Sabo",
  "Punjabi University, Patiala",
  "Punyashlok Ahilyadevi Holkar Solapur University",
  "Purnea University",
  "Quantum University",
  "Rabindra Bharati University",
  "Rabindranath Tagore University",
  "Radha Govind University",
  "Rai Technology University",
  "Rai University",
  "Raichur University",
  "Raiganj University",
  "Raj Rishi Bhartrihari Matsya University, Alwar",
  "Raja Mahendra Pratap Singh State University",
  "Raja Mansingh Tomar Music & Arts University",
  "Rajasthan Technical University, Kota",
  "Rajasthan University of Veterinary and Animal Sciences, Bikaner",
  "Rajendra University",
  "Rajiv Gandhi Government Polytechnic",
  "Rajiv Gandhi Institute of Petroleum Technology, Raebareli",
  "Rajiv Gandhi National Aviation University",
  "Rajiv Gandhi National University of Law, Patiala",
  "Rajiv Gandhi Technical University",
  "Rajiv Gandhi University",
  "Rajiv Gandhi University of Health Sciences",
  "Rajiv Gandhi University of Knowledge Technologies",
  "Rajiv Gandhi University of Knowledge Technologies, Nuzvid",
  "Rajmata Vijayaraje Scindia Krishi Vishwavidyalaya",
  "Ram Krishna Dharmarth Foundation University",
  "Rama Devi Women's University",
  "Rama University",
  "Ramakrishna Mission Vivekananda Educational and Research Institute",
  "Ramchandra Chandravansi University",
  "Ranchi University",
  "Rani Awantibai Lodhi University, Sagar",
  "Rani Channamma University",
  "Rani Durgavati University",
  "Rani Lakshmi Bai Central Agricultural University",
  "Rani Rashmoni Green University",
  "Ras Bihari Bose Subharti University",
  "Rashtrasant Tukadoji Maharaj Nagpur University",
  "Rashtriya Raksha University",
  "Ravenshaw University",
  "Rayalaseema University",
  "Rayat Bahra University, Mohali",
  "Regional Medical Research Centre, Bhubaneswar",
  "REVA University",
  "Rishihood University",
  "RK University",
  "RKDF University",
  "RNB Global University, Bikaner",
  "Royal Global University",
  "RV University",
  "SN Bose National Centre for Basic Sciences, Kolkata",
  "Sadhu Ramchand Murmu University of Jhargram",
  "SAGE University",
  "Saha Institute of Nuclear Physics, Kolkata",
  "Sai Nath University",
  "Sai University",
  "SAM Global University",
  "Sam Higginbottom Institute of Agriculture, Technology and Sciences",
  "Sambalpur University",
  "Sampurnanand Sanskrit University",
  "Sanchi University of Buddhist-Indic Studies",
  "Sandip University, Sijoul",
  "Sangai International University",
  "Sanjay Gandhi Postgraduate Institute of Medical Sciences, Lucknow",
  "Sanskaram University",
  "Sanskriti University",
  "Sant Gadge Baba Amravati University",
  "Sant Longowal Institute of Engineering and Technology",
  "Santosh Medical College",
  "Sarala Birla University",
  "Sardar Bhagwan Singh University",
  "Sardar Patel University, Gujarat",
  "Sardar Patel University Balaghat",
  "Sardar Patel University Mandi",
  "Sardar Patel University of Police, Security and Criminal Justice, Jodhpur",
  "Sardar Vallabhbhai Patel International School of Textiles & Management, Coimbatore",
  "Sardar Vallabhbhai Patel University of Agriculture and Technology",
  "Sardarkrushinagar Dantiwada Agricultural University",
  "Sarguja University",
  "Sarvepalli Radhakrishnan University",
  "Satavahana University",
  "Sathyabama Institute of Science and Technology",
  "Satyajit Ray Film and Television Institute",
  "Saurashtra University",
  "Saveetha Amaravati University",
  "Saveetha Institute of Medical And Technical Sciences (SIMATS)",
  "Savitribai Phule Pune University",
  "School of Planning and Architecture, Bhopal",
  "School of Planning and Architecture, New Delhi",
  "School of Planning and Architecture, Vijayawada",
  "SDGI Global University",
  "Seacom Skills University",
  "Senate of Serampore College (University)",
  "Seshadripuram College",
  "Shaheed Bhagat Singh State University, Firozpur",
  "Shaheed Mahendra Karma Vishwavidyalaya",
  "Shaheed Nandkumar Patel University, Raigarh",
  "SASTRA University",
  "Sharda University",
  "Sharnbasva University",
  "Sher-e-Kashmir University of Agricultural Sciences and Technology of Jammu (SUASTJ)",
  "Sher-e-Kashmir University of Agricultural Sciences and Technology of Kashmir (SUASTK)",
  "Shiv Nadar University",
  "Shiv Nadar University, Greater Noida",
  "Shivaji University",
  "Shobhit Institute of Engineering & Technology",
  "Shobhit University",
  "Shoolini University",
  "Shree Guru Gobind Singh Tricentenary University, Budhera",
  "Shree Jagannath Sanskrit University",
  "Shree Om University",
  "Shree Somnath Sanskrit University",
  "Shreemati Nathibai Damodar Thackersey Women's University",
  "Shri Govind Guru University",
  "Shri Govindram Seksaria Institute of Technology and Science",
  "Shri Guru Ram Rai University",
  "Shri Khushan Das University, Hanumangarh",
  "Shri Krishna AYUSH University",
  "Shri Lal Bahadur Shastri National Sanskrit University",
  "Shri Mata Vaishno Devi University (SMVDU)",
  "Shri Ramswaroop Memorial University",
  "Shri Rawatpura Sarkar University",
  "Shri Vaishnav Vidyapeeth Vishwavidyalaya",
  "Shri Venkateshwara University",
  "Sibsagar University",
  "Siddharth University",
  "Siddhartha Academy of Higher Education",
  "Sidho Kanho Birsha University",
  "Sido Kanhu Murmu University",
  "Sikkim Alpine University",
  "Sikkim Manipal University",
  "Sikkim Professional University",
  "Sikkim University",
  "Siksha \"O\" Anusandhan",
  "Silicon University",
  "Silver Oak University",
  "Singhania University, Pacheri Bari, Jhunjhunu",
  "Sister Nivedita University",
  "Skyline Business School, Sonipat Campus",
  "Smt. Manjira Devi University",
  "Soban Singh Jeena University",
  "Sona Devi University",
  "South Asian University",
  "Sparsh Himalaya University",
  "Sports University of Haryana",
  "SR University",
  "Sree Narayanaguru Open University",
  "Sree Sankaracharya University of Sanskrit",
  "Sri Chandrasekharendra Saraswathi Viswa Mahavidyalaya (SCSVMV)",
  "Sri Dev Suman Uttarakhand University",
  "Sri Devraj Urs Academy of Higher Education and Research",
  "Sri Guru Granth Sahib World University, Fatehgarh Sahib",
  "Sri Guru Ram Das University of Health Sciences, Sri Amritsar",
  "Sri Guru Teg Bahadur State University of Law, Tarn Taran district",
  "Sri Karan Narendra Agriculture University, Jobner",
  "Sri Konda Laxman Telangana State Horticultural University",
  "Sri Krishnadevaraya University",
  "Sri Padmavati Mahila Visvavidyalayam",
  "Sri Ramachandra Institute of Higher Education and Research",
  "Sri Sai University",
  "Sri Sathya Sai Institute of Higher Learning",
  "Sri Satya Sai University of Technology & Medical Sciences",
  "Sri Siddhartha Academy of Higher Education",
  "Sri Sri Aniruddhadeva Sports University",
  "Sri Sri University",
  "Sri Venkateswara Institute of Medical Sciences",
  "Sri Venkateswara University",
  "Sri Venkateswara Vedic University",
  "Sri Venkateswara Veterinary University",
  "Sri Venkateswaraa University",
  "Srimanta Sankaradeva University of Health Sciences",
  "Srinath University",
  "Srinivas University",
  "SRM University, Kattankulathur",
  "SRM University, Ramapuram",
  "SRM University, Vadapalani",
  "SRM University, Tiruchirappalli",
  "SRM University, Amaravati",
  "SRM University, Delhi-NCR",
  "SRM University, Haryana",
  "SRM University, Sikkim",
  "St Aloysius University",
  "St Aloysius' College",
  "St Joseph University, Bengaluru",
  "St Joseph University, Nagaland",
  "St Joseph's College of Commerce",
  "St Joseph's University",
  "St Peter's Institute of Higher Education and Research",
  "St Xavier's University, Kolkata",
  "Starex University",
  "State University of Performing And Visual Arts",
  "Sumandeep Vidyapeeth",
  "Sunrise University, Alwar",
  "Surajmal University",
  "Suravaram Pratap Reddy Telugu University",
  "Suresh Gyan Vihar University, Jaipur",
  "Sushant University Gurgaon",
  "SVKM's NMIMS",
  "Swami Keshwanand Rajasthan Agricultural University, Bikaner",
  "Swami Rama Himalayan University",
  "Swami Ramanand Teerth Marathwada University",
  "Swami Vivekanand National Institute of Rehabilitation Training and Research",
  "Swami Vivekanand Subharti University",
  "Swami Vivekanand University, Kokrajhar",
  "Swami Vivekanand University, Sagar",
  "Swami Vivekananda University, Barrackpore",
  "Swami Vivekananda Yoga Anusandhana Samsthana",
  "Swarnim Gujarat Sports University",
  "Symbiosis International University",
  "Takshashila University, Tamilnadu",
  "Tamil Nadu Agricultural University",
  "Tamil Nadu Dr J Jayalalithaa Fisheries University",
  "Tamil Nadu National Law School",
  "Tamil Nadu National Law University",
  "Tamil Nadu Open University",
  "Tamil Nadu Physical Education and Sports University",
  "Tamil Nadu Teachers Education University",
  "Tamil Nadu Veterinary and Animal Sciences University",
  "Tamil University",
  "Tamil Virtual Academy",
  "Tantia University, Sri Ganganagar",
  "Tata Institute of Fundamental Research Hyderabad",
  "Tata Institute of Social Sciences, Mumbai",
  "Tata Institute of Social Sciences, Hyderabad",
  "TCG CREST",
  "Techno Global University",
  "Techno India University, Kolkata",
  "Techno India University, Tripura",
  "Teerthanker Mahaveer University",
  "Telangana University",
  "Tezpur University",
  "Thapar Institute of Engineering and Technology, Patiala",
  "The Apollo University",
  "The Central Sanskrit University, New Delhi",
  "The English and Foreign Languages University",
  "The Gandhigram Rural Institute",
  "The Global Open University, Chumoukedima",
  "The Global University",
  "The Glocal University",
  "ICFAI Foundation for Higher Education, Hyderabad",
  "ICFAI University, Dehradun",
  "ICFAI University, Himachal Pradesh",
  "ICFAI University, Jaipur",
  "ICFAI University, Jharkhand",
  "ICFAI University, Mizoram",
  "ICFAI University, Nagaland",
  "The Indian Institute of Cosmetology, Aesthetics, and Nutrition (I2CAN)",
  "The Neotia University",
  "The NorthCap University",
  "The Sanskrit College and University",
  "The Tamil Nadu Dr Ambedkar Law University",
  "The Tamil Nadu Dr J Jayalalithaa Music and Fine Arts University",
  "The Tamil Nadu Dr MGR Medical University",
  "The University of North West Himalayas",
  "Thiruvalluvar University",
  "Thunchath Ezhuthachan Malayalam University",
  "Tilak Maharashtra University",
  "Tilka Manjhi Bhagalpur University",
  "Tomi Polytechnic College",
  "Tomo Riba Institute of Health and Medical Sciences",
  "Tripura Institute of Technology",
  "Tripura University",
  "Tumkur University",
  "UP Pt Deen Dayal Upadhyaya Veterinary Science University and Cattle Research Institute",
  "Udai Pratap Autonomous College",
  "Uka Tarsadia University",
  "United University",
  "Universal Ai University, Karjat",
  "Universal Group Of Institutions, Mohali",
  "University of Agricultural and Horticultural Sciences, Shivamogga",
  "University of Agricultural Sciences, Bangalore",
  "University of Agricultural Sciences, Dharwad",
  "University of Agricultural Sciences, Raichur",
  "University of Allahabad",
  "University of Bongaigaon",
  "University of Burdwan",
  "University of Calcutta",
  "University of Calicut",
  "University of Engineering & Management (UEM), Jaipur",
  "University of Engineering & Management (UEM), Kolkata",
  "University of Gour Banga",
  "University of Horticultural Sciences, Bagalkot",
  "University of Hyderabad",
  "University of Jammu",
  "University of Kalyani",
  "University of Kashmir",
  "University of Kerala",
  "University of Kota",
  "University of Ladakh",
  "University of Lucknow",
  "University of Madras",
  "University of Mumbai",
  "University of Mysore",
  "University of North Bengal",
  "University of Patanjali",
  "University of Petroleum and Energy Studies",
  "University of Rajasthan",
  "University of Science and Technology Meghalaya",
  "Usha Martin University",
  "Usha Mittal Institute of Technology",
  "Utkal University",
  "Utkal University of Culture",
  "Uttar Banga Krishi Vishwavidyalaya",
  "Uttar Pradesh Rajarshi Tandon Open University",
  "Uttar Pradesh University of Medical Sciences",
  "Uttarakhand Aawasiya Vishwavidyalaya",
  "Uttarakhand Ayurveda University",
  "Uttarakhand Open University",
  "Uttarakhand Sanskrit University",
  "Uttarakhand State Sports University",
  "Uttaranchal University",
  "Vardhaman Mahaveer Open University, Kota",
  "Variable Energy Cyclotron Centre, Kolkata",
  "Vasantrao Naik Marathwada Agricultural University",
  "Vasireddy Venkatadri International Technological University",
  "Veer Bahadur Singh Purvanchal University",
  "Veer Chandra Singh Garhwali Uttarakhand University of Horticulture and Forestry",
  "Veer Kunwar Singh University",
  "Veer Madho Singh Bhandari Uttarakhand Technical University",
  "Veer Narmad South Gujarat University",
  "Veer Surendra Sai University of Technology",
  "Vel Tech Rangarajan Dr. Sagunthala R&D Institute of Science and Technology",
  "Vellore Institute of Technology (VIT)",
  "Vels Institute of Science, Technology & Advanced Studies (VISTAS)",
  "Veltech University",
  "Venkateshwara Open University",
  "Vidyasagar University",
  "Vignan's Foundation for Science, Technology & Research",
  "Vijayanagara Sri Krishnadevaraya University",
  "Vikram Dev University",
  "Vikram University",
  "Vikrama Simhapuri University",
  "Vikrant University",
  "Vinayaka Mission's Research Foundation",
  "Vinoba Bhave University",
  "Visva-Bharati University, Shantiniketan",
  "Visvesvaraya National Institute of Technology, Nagpur",
  "Visvesvaraya Technological University",
  "Visvesvaraya Technological University (VTU), Belagavi",
  "VIT-AP University",
  "Vivekananda Global University, Jaipur",
  "West Bengal National University of Juridical Sciences, Kolkata",
  "West Bengal State University",
  "West Bengal University of Animal and Fishery Sciences",
  "West Bengal University of Health Sciences",
  "William Carey University, Meghalaya",
  "World University of Design",
  "Woxsen University",
  "Xavier Institute of Development Action and Studies",
  "XIM University",
  "Yashwantrao Chavan Maharashtra Open University",
  "YBN University",
  "Yenepoya University",
  "Yenepoya University, Mangaluru",
  "Yogi Vemana University"
];
