import { CommonModule } from '@angular/common';
import { Component } from '@angular/core';
import { FormsModule } from '@angular/forms';
import { ActivatedRoute, RouterLink } from '@angular/router';
import { StudentWorkspaceRailComponent } from './student-workspace-rail.component';

@Component({standalone:true,imports:[CommonModule,FormsModule,RouterLink,StudentWorkspaceRailComponent],styleUrl:'./student-extra-page.component.css',template:`
<app-student-workspace-rail />
<main class="student-extra">
  <header><div><span>STUDENT WORKSPACE</span><h1>{{title}}</h1><p>{{description}}</p></div><a *ngIf="actionRoute" [routerLink]="actionRoute">{{actionLabel}}</a></header>
  <div class="search" *ngIf="page==='saved-universities'||page==='scholarships'"><label>⌕<input [(ngModel)]="query" placeholder="Search universities or programmes"></label><select [(ngModel)]="filter"><option>All destinations</option><option>Canada</option><option>United Kingdom</option></select></div>
  <section class="grid" *ngIf="page==='saved-universities'||page==='scholarships'">
    <article *ngFor="let item of filteredCards"><div class="logo">{{item.initial}}</div><span>{{item.tag}}</span><h2>{{item.title}}</h2><p>{{item.detail}}</p><div class="terms"><small>{{item.meta}}</small><strong>{{item.value}}</strong></div><footer><button (click)="saved=!saved">{{saved?'✓ Saved':'☆ Save'}}</button><a routerLink="/student/offers">View details →</a></footer></article>
  </section>
  <section class="loan" *ngIf="page==='loan-eligibility'">
    <form #loanForm="ngForm" (ngSubmit)="checkEligibility(loanForm.valid)"><h2>Check your indicative eligibility</h2><p>Adjust the details below to preview matched funding.</p><div><label>Study destination<select name="destination" required [(ngModel)]="destination"><option>Canada</option><option>United Kingdom</option><option>United States</option></select></label><label>Course level<select name="level" required [(ngModel)]="level"><option>Postgraduate</option><option>Undergraduate</option></select></label><label>Estimated course cost (₹)<input name="cost" required type="number" min="100000" [(ngModel)]="cost"></label><label>Co-applicant monthly income (₹)<input name="income" required type="number" min="10000" [(ngModel)]="income"></label></div><button [disabled]="loanForm.invalid">Check eligibility</button></form>
    <aside *ngIf="checked"><span>INDICATIVE RESULT</span><b>✓</b><h2>You may be eligible</h2><strong>Up to ₹35 lakh</strong><p>Matched with 3 verified education finance partners.</p><a routerLink="/student/offers">View funding offers →</a><small>This is not a credit decision or guaranteed offer.</small></aside>
    <aside class="empty" *ngIf="!checked"><b>₹</b><h2>Your estimate will appear here</h2><p>Complete the form to see a mock eligibility result.</p></aside>
  </section>
  <section class="notifications" *ngIf="page==='notifications'"><header><h2>Recent updates</h2><button (click)="markAll()">Mark all read</button></header><article *ngFor="let note of notes" [class.unread]="!note.read"><i>{{note.icon}}</i><div><strong>{{note.title}}</strong><p>{{note.text}}</p><small>{{note.time}}</small></div><button (click)="note.read=true">{{note.read?'Read':'Mark read'}}</button></article></section>
  <section class="messages" *ngIf="page==='messages'"><aside><button *ngFor="let contact of contacts" [class.active]="selected===contact" (click)="selected=contact"><i>{{contact.initial}}</i><div><strong>{{contact.name}}</strong><small>{{contact.role}}</small></div></button></aside><div><header><i>{{selected.initial}}</i><div><strong>{{selected.name}}</strong><small>{{selected.role}}</small></div></header><section><p><span>{{selected.message}}</span><small>Today, 10:14</small></p><p class="mine"><span>Thank you. I’ll review it today.</span><small>Today, 10:20</small></p></section><form (ngSubmit)="send()"><input name="draft" [(ngModel)]="draft" placeholder="Write a message…"><button [disabled]="!draft.trim()">Send</button></form></div></section>
</main>`})
export class StudentExtraPageComponent{
 page='saved-universities';query='';filter='All destinations';saved=true;checked=false;destination='Canada';level='Postgraduate';cost=3500000;income=90000;draft='';
 cards=[{initial:'N',tag:'CANADA · FALL 2027',title:'Northbridge University',detail:'MSc Data Science · Toronto',meta:'Application fee waived',value:'40% scholarship'},{initial:'W',tag:'UNITED KINGDOM · SEP 2027',title:'Westford University',detail:'MSc Artificial Intelligence · Manchester',meta:'Priority admission',value:'£6,000 award'},{initial:'L',tag:'CANADA · JAN 2028',title:'Lakeview University',detail:'Master of Business Analytics · Vancouver',meta:'Profile match 88%',value:'Up to 25%'}];
 notes=[{icon:'✦',title:'New scholarship match',text:'Northbridge University matched you with its Global Excellence Scholarship.',time:'10 minutes ago',read:false},{icon:'✉',title:'New message',text:'Maya Chen replied to your question about scholarship renewal.',time:'1 hour ago',read:false},{icon:'▤',title:'Document reminder',text:'Upload your final transcript before 20 August.',time:'Yesterday',read:true}];
 contacts=[{initial:'M',name:'Maya Chen',role:'Northbridge University',message:'Your scholarship is renewable for the second year.'},{initial:'R',name:'Rohan Kapoor',role:'EduFund Finance',message:'I can help with the co-applicant documents.'},{initial:'S',name:'SuperOffer Support',role:'Student support',message:'How can we help with your journey?'}];selected=this.contacts[0];
 constructor(route:ActivatedRoute){route.data.subscribe(d=>this.page=d['page']);}
 get title(){return {'saved-universities':'Saved universities',scholarships:'Scholarships','loan-eligibility':'Loan eligibility',notifications:'Notifications',messages:'Messages'}[this.page]||'Student workspace';}
 get description(){return {'saved-universities':'Compare universities you want to revisit.',scholarships:'Explore awards matched to your profile and goals.','loan-eligibility':'Preview potential education finance matches.',notifications:'Stay on top of offers, documents, and deadlines.',messages:'Speak with universities, lenders, and support.'}[this.page]||'';}
 get actionRoute(){return this.page==='saved-universities'?'/student/offers':this.page==='scholarships'?'/student/study-preferences':'';} get actionLabel(){return this.page==='saved-universities'?'Explore offers':'Update preferences';}
 get filteredCards(){const q=this.query.toLowerCase();return this.cards.filter(x=>!q||`${x.title} ${x.detail}`.toLowerCase().includes(q));} checkEligibility(valid:boolean|null){this.checked=!!valid;} markAll(){this.notes.forEach(x=>x.read=true);} send(){if(!this.draft.trim())return;this.selected.message=this.draft;this.draft='';}
}
